/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub const BLEND_COLOR_SOURCE: u32 = 0;
pub const BLEND_COLOR_DEST: u32 = 1;
pub const BLEND_COLOR_ZERO: u32 = 2;
pub const BLEND_ALPHA_SOURCE: u32 = 0;
pub const BLEND_ALPHA_DEST: u32 = 1;
pub const BLEND_ALPHA_FIXED: u32 = 2;
pub const ALPHA_CORRECT_RGBA32: u32 = 0;
pub const ALPHA_CORRECT_RGBA16: u32 = 1;
pub const TEXTURE_COMPONENTS_RGB: u32 = 0;
pub const TEXTURE_COMPONENTS_RGBA: u32 = 1;
pub const TEXTURE_FUNCTION_MODULATE: u32 = 0;
pub const TEXTURE_FUNCTION_DECAL: u32 = 1;
pub const TEXTURE_FUNCTION_HIGHLIGHT: u32 = 2;
pub const TEXTURE_FUNCTION_HIGHLIGHT2: u32 = 3;
pub const CLUT_STORAGE_MODE1: u32 = 0;
pub const CLUT_STORAGE_MODE2: u32 = 1;
pub const CLUT_NO_LOAD: u32 = 0;
pub const CLUT_LOAD: u32 = 1;
pub const CLUT_LOAD_COPY_CBP0: u32 = 2;
pub const CLUT_LOAD_COPY_CBP1: u32 = 3;
pub const CLUT_COMPARE_CBP0: u32 = 4;
pub const CLUT_COMPARE_CBP1: u32 = 5;
pub const SCAN_MASK_NORMAL: u32 = 0;
pub const SCAN_MASK_ODD: u32 = 2;
pub const SCAN_MASK_EVEN: u32 = 3;
pub const COLOR_CLAMP_MASK: u32 = 0;
pub const COLOR_CLAMP_ENABLE: u32 = 1;
pub const PRIM_POINT: u32 = 0;
pub const PRIM_LINE: u32 = 1;
pub const PRIM_LINE_STRIP: u32 = 2;
pub const PRIM_TRIANGLE: u32 = 3;
pub const PRIM_TRIANGLE_STRIP: u32 = 4;
pub const PRIM_TRIANGLE_FAN: u32 = 5;
pub const PRIM_SPRITE: u32 = 6;
pub const PRIM_SHADE_FLAT: u32 = 0;
pub const PRIM_SHADE_GOURAUD: u32 = 1;
pub const PRIM_MAP_ST: u32 = 0;
pub const PRIM_MAP_UV: u32 = 1;
pub const PRIM_UNFIXED: u32 = 0;
pub const PRIM_FIXED: u32 = 1;
pub const PRIM_OVERRIDE_ENABLE: u32 = 0;
pub const PRIM_OVERRIDE_DISABLE: u32 = 1;
pub const LOD_FORMULAIC: u32 = 0;
pub const LOD_USE_K: u32 = 1;
pub const LOD_MAG_NEAREST: u32 = 0;
pub const LOD_MAG_LINEAR: u32 = 1;
pub const LOD_MIN_NEAREST: u32 = 0;
pub const LOD_MIN_LINEAR: u32 = 1;
pub const LOD_MIN_NEAR_MIPMAP_NEAR: u32 = 2;
pub const LOD_MIN_NEAR_MIPMAP_LINE: u32 = 3;
pub const LOD_MIN_LINE_MIPMAP_NEAR: u32 = 4;
pub const LOD_MIN_LINE_MIPMAP_LINE: u32 = 5;
pub const LOD_MIPMAP_REGISTER: u32 = 0;
pub const LOD_MIPMAP_CALCULATE: u32 = 1;
pub const WRAP_REPEAT: u32 = 0;
pub const WRAP_CLAMP: u32 = 1;
pub const WRAP_REGION_CLAMP: u32 = 2;
pub const WRAP_REGION_REPEAT: u32 = 3;
pub const ALPHA_EXPAND_NORMAL: u32 = 0;
pub const ALPHA_EXPAND_TRANSPARENT: u32 = 1;
pub const ATEST_METHOD_ALLFAIL: u32 = 0;
pub const ATEST_METHOD_ALLPASS: u32 = 1;
pub const ATEST_METHOD_LESS: u32 = 2;
pub const ATEST_METHOD_LESS_EQUAL: u32 = 3;
pub const ATEST_METHOD_EQUAL: u32 = 4;
pub const ATEST_METHOD_GREATER_EQUAL: u32 = 5;
pub const ATEST_METHOD_GREATER: u32 = 6;
pub const ATEST_METHOD_NOTEQUAL: u32 = 7;
pub const ATEST_KEEP_ALL: u32 = 0;
pub const ATEST_KEEP_ZBUFFER: u32 = 1;
pub const ATEST_KEEP_FRAMEBUFFER: u32 = 2;
pub const ATEST_KEEP_ALPHA: u32 = 3;
pub const DTEST_METHOD_PASS_ZERO: u32 = 0;
pub const DTEST_METHOD_PASS_ONE: u32 = 1;
pub const ZTEST_METHOD_ALLFAIL: u32 = 0;
pub const ZTEST_METHOD_ALLPASS: u32 = 1;
pub const ZTEST_METHOD_GREATER_EQUAL: u32 = 2;
pub const ZTEST_METHOD_GREATER: u32 = 3;
pub const LIGHT_AMBIENT: u32 = 0;
pub const LIGHT_DIRECTIONAL: u32 = 1;
pub const GIF_BLOCK_SIZE: u32 = 32767;
pub const GIF_PRE_DISABLE: u32 = 0;
pub const GIF_PRE_ENABLE: u32 = 1;
pub const GIF_PRIM_POINT: u32 = 0;
pub const GIF_PRIM_LINE: u32 = 1;
pub const GIF_PRIM_LINE_STRIP: u32 = 2;
pub const GIF_PRIM_TRIANGLE: u32 = 3;
pub const GIF_PRIM_TRIANGLE_STRIP: u32 = 4;
pub const GIF_PRIM_TRIANGLE_FAN: u32 = 5;
pub const GIF_PRIM_SPRITE: u32 = 6;
pub const GIF_FLG_PACKED: u32 = 0;
pub const GIF_FLG_REGLIST: u32 = 1;
pub const GIF_FLG_IMAGE: u32 = 2;
pub const GIF_REG_PRIM: u32 = 0;
pub const GIF_REG_RGBAQ: u32 = 1;
pub const GIF_REG_ST: u32 = 2;
pub const GIF_REG_UV: u32 = 3;
pub const GIF_REG_XYZF2: u32 = 4;
pub const GIF_REG_XYZ2: u32 = 5;
pub const GIF_REG_TEX0: u32 = 6;
pub const GIF_REG_TEX0_1: u32 = 6;
pub const GIF_REG_TEX0_2: u32 = 7;
pub const GIF_REG_CLAMP: u32 = 8;
pub const GIF_REG_CLAMP_1: u32 = 8;
pub const GIF_REG_CLAMP_2: u32 = 9;
pub const GIF_REG_FOG: u32 = 10;
pub const GIF_REG_XYZF3: u32 = 12;
pub const GIF_REG_XYZ3: u32 = 13;
pub const GIF_REG_AD: u32 = 14;
pub const GIF_REG_NOP: u32 = 15;
pub const DRAW_DISABLE: u32 = 0;
pub const DRAW_ENABLE: u32 = 1;
pub const __NEWLIB_H__: u32 = 1;
pub const _NEWLIB_VERSION_H__: u32 = 1;
pub const _NEWLIB_VERSION: &[u8; 6] = b"4.6.0\0";
pub const __NEWLIB__: u32 = 4;
pub const __NEWLIB_MINOR__: u32 = 6;
pub const __NEWLIB_PATCHLEVEL__: u32 = 0;
pub const _ATEXIT_DYNAMIC_ALLOC: u32 = 1;
pub const _FSEEK_OPTIMIZATION: u32 = 1;
pub const _FVWRITE_IN_STREAMIO: u32 = 1;
pub const _HAVE_CC_INHIBIT_LOOP_TO_LIBCALL: u32 = 1;
pub const _HAVE_INITFINI_ARRAY: u32 = 1;
pub const _HAVE_LONG_DOUBLE: u32 = 1;
pub const _LDBL_EQ_DBL: u32 = 1;
pub const _MB_LEN_MAX: u32 = 1;
pub const _REENT_CHECK_VERIFY: u32 = 1;
pub const _RETARGETABLE_LOCKING: u32 = 1;
pub const _UNBUF_STREAM_OPT: u32 = 1;
pub const _WANT_IO_C99_FORMATS: u32 = 1;
pub const _WANT_IO_LONG_LONG: u32 = 1;
pub const _WANT_USE_GDTOA: u32 = 1;
pub const _WIDE_ORIENT: u32 = 1;
pub const __OBSOLETE_MATH_DEFAULT: u32 = 1;
pub const __OBSOLETE_MATH: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 202405;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __ATFILE_VISIBLE: u32 = 1;
pub const __BSD_VISIBLE: u32 = 1;
pub const __GNU_VISIBLE: u32 = 0;
pub const __ISO_C_VISIBLE: u32 = 2011;
pub const __LARGEFILE_VISIBLE: u32 = 0;
pub const __MISC_VISIBLE: u32 = 1;
pub const __POSIX_VISIBLE: u32 = 202405;
pub const __SVID_VISIBLE: u32 = 1;
pub const __XSI_VISIBLE: u32 = 0;
pub const __SSP_FORTIFY_LEVEL: u32 = 0;
pub const MALLOC_ALIGNMENT: u32 = 16;
pub const __RAND_MAX: u32 = 2147483647;
pub const PACKET2_COUNT_QWC: u32 = 65536;
pub type u8_ = ::core::ffi::c_uchar;
pub type u16_ = ::core::ffi::c_ushort;
pub type u32_ = ::core::ffi::c_uint;
pub type u64_ = ::core::ffi::c_ulonglong;
pub type u128_ = u128;
pub type s8 = ::core::ffi::c_schar;
pub type s16 = ::core::ffi::c_short;
pub type vs8 = s8;
pub type vs16 = s16;
pub type s32 = ::core::ffi::c_int;
pub type s64 = ::core::ffi::c_longlong;
pub type s128 = i128;
pub type vs32 = s32;
pub type vs64 = s64;
pub type vs128 = i128;
pub type uiptr = u32_;
pub type siptr = s32;
pub type vuiptr = u32_;
pub type vsiptr = s32;
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union qword_t {
    pub qw: u128_,
    pub b: [u8_; 16usize],
    pub hw: [u16_; 8usize],
    pub sw: [u32_; 4usize],
    pub dw: [u64_; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct blend_t {
    pub color1: ::core::ffi::c_char,
    pub color2: ::core::ffi::c_char,
    pub alpha: ::core::ffi::c_char,
    pub color3: ::core::ffi::c_char,
    pub fixed_alpha: ::core::ffi::c_uchar,
}
unsafe extern "C" {
    #[doc = " Alpha Blending Per-Pixel MSB Control"]
    pub fn draw_pixel_alpha_control(q: *mut qword_t, enable: ::core::ffi::c_int) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Alpha Blending"]
    pub fn draw_alpha_blending(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        blend: *mut blend_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Alpha Correction"]
    pub fn draw_alpha_correction(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        alpha: ::core::ffi::c_int,
    ) -> *mut qword_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct texinfo_t {
    pub width: ::core::ffi::c_uchar,
    pub height: ::core::ffi::c_uchar,
    pub components: ::core::ffi::c_uchar,
    pub function: ::core::ffi::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct framebuffer_t {
    pub address: ::core::ffi::c_uint,
    pub width: ::core::ffi::c_uint,
    pub height: ::core::ffi::c_uint,
    pub psm: ::core::ffi::c_uint,
    pub mask: ::core::ffi::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct zbuffer_t {
    pub enable: ::core::ffi::c_uint,
    pub method: ::core::ffi::c_uint,
    pub address: ::core::ffi::c_uint,
    pub zsm: ::core::ffi::c_uint,
    pub mask: ::core::ffi::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct texbuffer_t {
    pub address: ::core::ffi::c_uint,
    pub width: ::core::ffi::c_uint,
    pub psm: ::core::ffi::c_uint,
    pub info: texinfo_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clutbuffer_t {
    pub address: ::core::ffi::c_uint,
    pub psm: ::core::ffi::c_uint,
    pub storage_mode: ::core::ffi::c_uint,
    pub start: ::core::ffi::c_uint,
    pub load_method: ::core::ffi::c_uint,
}
unsafe extern "C" {
    #[doc = " Returns the power of 2 needed for texture width and height"]
    pub fn draw_log2(x: ::core::ffi::c_uint) -> ::core::ffi::c_uchar;
}
unsafe extern "C" {
    #[doc = " Framebuffer Attributes"]
    pub fn draw_framebuffer(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        frame: *mut framebuffer_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " ZBuffer Attributes"]
    pub fn draw_zbuffer(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        zbuffer: *mut zbuffer_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " TextureBuffer Attributes"]
    pub fn draw_texturebuffer(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        texbuffer: *mut texbuffer_t,
        clut: *mut clutbuffer_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " CLUT Storage Mode 1 Information"]
    pub fn draw_clutbuffer(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        psm: ::core::ffi::c_int,
        clut: *mut clutbuffer_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " CLUT Storage Mode 2 Information"]
    pub fn draw_clut_offset(
        q: *mut qword_t,
        cbw: ::core::ffi::c_int,
        u: ::core::ffi::c_int,
        v: ::core::ffi::c_int,
    ) -> *mut qword_t;
}
pub type dithermx_t = [::core::ffi::c_schar; 16usize];
unsafe extern "C" {
    #[doc = " Dithering Switch"]
    pub fn draw_dithering(q: *mut qword_t, enable: ::core::ffi::c_int) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Dithering Matrix"]
    pub fn draw_dither_matrix(q: *mut qword_t, dm: *mut ::core::ffi::c_char) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Fog Color"]
    pub fn draw_fog_color(
        q: *mut qword_t,
        r: ::core::ffi::c_uchar,
        g: ::core::ffi::c_uchar,
        b: ::core::ffi::c_uchar,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Scanline Masking (framebuffer)"]
    pub fn draw_scan_masking(q: *mut qword_t, mask: ::core::ffi::c_int) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Color Masking/Clamping"]
    pub fn draw_color_clamping(q: *mut qword_t, enable: ::core::ffi::c_int) -> *mut qword_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct prim_t {
    pub type_: ::core::ffi::c_uchar,
    pub shading: ::core::ffi::c_uchar,
    pub mapping: ::core::ffi::c_uchar,
    pub fogging: ::core::ffi::c_uchar,
    pub blending: ::core::ffi::c_uchar,
    pub antialiasing: ::core::ffi::c_uchar,
    pub mapping_type: ::core::ffi::c_uchar,
    pub colorfix: ::core::ffi::c_uchar,
}
unsafe extern "C" {
    #[doc = " Primitive Coordinate System offset"]
    pub fn draw_primitive_xyoffset(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        x: f32,
        y: f32,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Primitive Control"]
    pub fn draw_primitive_override(q: *mut qword_t, mode: ::core::ffi::c_int) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Overridden Primitive Attributes"]
    pub fn draw_primitive_override_setting(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        prim: *mut prim_t,
    ) -> *mut qword_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lod_t {
    pub calculation: ::core::ffi::c_uchar,
    pub max_level: ::core::ffi::c_uchar,
    pub mag_filter: ::core::ffi::c_uchar,
    pub min_filter: ::core::ffi::c_uchar,
    pub mipmap_select: ::core::ffi::c_uchar,
    pub l: ::core::ffi::c_uchar,
    pub k: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mipmap_t {
    pub address1: ::core::ffi::c_int,
    pub address2: ::core::ffi::c_int,
    pub address3: ::core::ffi::c_int,
    pub width1: ::core::ffi::c_char,
    pub width2: ::core::ffi::c_char,
    pub width3: ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct texwrap_t {
    pub horizontal: ::core::ffi::c_uchar,
    pub vertical: ::core::ffi::c_uchar,
    pub minu: ::core::ffi::c_int,
    pub maxu: ::core::ffi::c_int,
    pub minv: ::core::ffi::c_int,
    pub maxv: ::core::ffi::c_int,
}
unsafe extern "C" {
    #[doc = " Texture Sampling, Level-of-Detail, and Filtering"]
    pub fn draw_texture_sampling(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        lod: *mut lod_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Mipmap levels 1-3"]
    pub fn draw_mipmap1(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        mipmap: *mut mipmap_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Mipmap levels 4-6"]
    pub fn draw_mipmap2(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        mipmap: *mut mipmap_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Texture Clamping"]
    pub fn draw_texture_wrapping(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        wrap: *mut texwrap_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Alpha Expansion Values"]
    pub fn draw_texture_expand_alpha(
        q: *mut qword_t,
        zero_value: ::core::ffi::c_uchar,
        expand: ::core::ffi::c_int,
        one_value: ::core::ffi::c_uchar,
    ) -> *mut qword_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atest_t {
    pub enable: ::core::ffi::c_uchar,
    pub method: ::core::ffi::c_uchar,
    pub compval: ::core::ffi::c_uchar,
    pub keep: ::core::ffi::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dtest_t {
    pub enable: ::core::ffi::c_uchar,
    pub pass: ::core::ffi::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ztest_t {
    pub enable: ::core::ffi::c_uchar,
    pub method: ::core::ffi::c_uchar,
}
unsafe extern "C" {
    #[doc = " Scissoring pixel test area"]
    pub fn draw_scissor_area(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        x0: ::core::ffi::c_int,
        x1: ::core::ffi::c_int,
        y0: ::core::ffi::c_int,
        y1: ::core::ffi::c_int,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Pixel Testing"]
    pub fn draw_pixel_test(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        atest: *mut atest_t,
        dtest: *mut dtest_t,
        ztest: *mut ztest_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Disable pixel testing defaults"]
    pub fn draw_disable_tests(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        z: *mut zbuffer_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Enable pixel testing defaults"]
    pub fn draw_enable_tests(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        z: *mut zbuffer_t,
    ) -> *mut qword_t;
}
pub type VECTOR = [f32; 4usize];
pub type MATRIX = [f32; 16usize];
unsafe extern "C" {
    #[doc = " Multiply a vector by a matrix, returning a vector."]
    pub fn vector_apply(output: *mut f32, input0: *mut f32, input1: *mut f32);
}
unsafe extern "C" {
    #[doc = " Clamp a vector's values by cutting them off at a minimum and maximum value."]
    pub fn vector_clamp(output: *mut f32, input0: *mut f32, min: f32, max: f32);
}
unsafe extern "C" {
    #[doc = " Copy a vector."]
    pub fn vector_copy(output: *mut f32, input0: *mut f32);
}
unsafe extern "C" {
    #[doc = " Calculate the inner product of two vectors. Returns a scalar value."]
    pub fn vector_innerproduct(input0: *mut f32, input1: *mut f32) -> f32;
}
unsafe extern "C" {
    #[doc = " Multiply two vectors together."]
    pub fn vector_multiply(output: *mut f32, input0: *mut f32, input1: *mut f32);
}
unsafe extern "C" {
    #[doc = " Normalize a vector by determining its length and dividing its values by this value."]
    pub fn vector_normalize(output: *mut f32, input0: *mut f32);
}
unsafe extern "C" {
    #[doc = " Calculate the outer product of two vectors."]
    pub fn vector_outerproduct(output: *mut f32, input0: *mut f32, input1: *mut f32);
}
unsafe extern "C" {
    #[doc = " Add two vectors"]
    pub fn vector_add(sum: *mut f32, addend: *mut f32, summand: *mut f32);
}
unsafe extern "C" {
    #[doc = " Calculate the cross product of two vectors"]
    pub fn vector_cross_product(product: *mut f32, multiplicand: *mut f32, multiplier: *mut f32);
}
unsafe extern "C" {
    #[doc = " Calculates the normal of 3 vectors"]
    pub fn vector_triangle_normal(output: *mut f32, a: *mut f32, b: *mut f32, c: *mut f32);
}
unsafe extern "C" {
    #[doc = " Copy a matrix."]
    pub fn matrix_copy(output: *mut f32, input0: *mut f32);
}
unsafe extern "C" {
    #[doc = " Calculate the inverse of a matrix."]
    pub fn matrix_inverse(output: *mut f32, input0: *mut f32);
}
unsafe extern "C" {
    #[doc = " Multiply two matrices together."]
    pub fn matrix_multiply(output: *mut f32, input0: *mut f32, input1: *mut f32);
}
unsafe extern "C" {
    #[doc = " Create a rotation matrix and apply it to the specified input matrix."]
    pub fn matrix_rotate(output: *mut f32, input0: *mut f32, input1: *mut f32);
}
unsafe extern "C" {
    #[doc = " Create a scaling matrix and apply it to the specified input matrix."]
    pub fn matrix_scale(output: *mut f32, input0: *mut f32, input1: *mut f32);
}
unsafe extern "C" {
    #[doc = " Create a translation matrix and apply it to the specified input matrix."]
    pub fn matrix_translate(output: *mut f32, input0: *mut f32, input1: *mut f32);
}
unsafe extern "C" {
    #[doc = " Transpose a matrix."]
    pub fn matrix_transpose(output: *mut f32, input0: *mut f32);
}
unsafe extern "C" {
    #[doc = " Create a unit matrix."]
    pub fn matrix_unit(output: *mut f32);
}
unsafe extern "C" {
    #[doc = " Create a local_world matrix given a translation and rotation.\n Commonly used to describe an object's position and orientation."]
    pub fn create_local_world(local_world: *mut f32, translation: *mut f32, rotation: *mut f32);
}
unsafe extern "C" {
    #[doc = " Create a local_light matrix given a rotation.\n Commonly used to transform an object's normals for lighting calculations."]
    pub fn create_local_light(local_light: *mut f32, rotation: *mut f32);
}
unsafe extern "C" {
    #[doc = " Create a world_view matrix given a translation and rotation.\n Commonly used to describe a camera's position and rotation."]
    pub fn create_world_view(world_view: *mut f32, translation: *mut f32, rotation: *mut f32);
}
unsafe extern "C" {
    #[doc = " Create a view_screen matrix given an aspect and clipping plane values.\n Functionally similar to the opengl function: glFrustum()"]
    pub fn create_view_screen(
        view_screen: *mut f32,
        aspect: f32,
        left: f32,
        right: f32,
        bottom: f32,
        top: f32,
        near: f32,
        far: f32,
    );
}
unsafe extern "C" {
    #[doc = " Create a local_screen matrix given a local_world, world_view and view_screen matrix.\n Commonly used with vector_apply() to transform vertices for rendering."]
    pub fn create_local_screen(
        local_screen: *mut f32,
        local_world: *mut f32,
        world_view: *mut f32,
        view_screen: *mut f32,
    );
}
unsafe extern "C" {
    #[doc = " Transform an array of normals by applying the specified local_light matrix."]
    pub fn calculate_normals(
        output: *mut VECTOR,
        count: ::core::ffi::c_int,
        normals: *mut VECTOR,
        local_light: *mut f32,
    );
}
unsafe extern "C" {
    #[doc = " Calculate the light intensity for an array of lights given an array of normal values."]
    pub fn calculate_lights(
        output: *mut VECTOR,
        count: ::core::ffi::c_int,
        normals: *mut VECTOR,
        light_directions: *mut VECTOR,
        light_colours: *mut VECTOR,
        light_types: *const ::core::ffi::c_int,
        light_count: ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    #[doc = " Calculate colour values given an array of light intensity values."]
    pub fn calculate_colours(
        output: *mut VECTOR,
        count: ::core::ffi::c_int,
        colours: *mut VECTOR,
        lights: *mut VECTOR,
    );
}
unsafe extern "C" {
    #[doc = " Calculate vertex values by applying the specific local_screen matrix."]
    pub fn calculate_vertices(
        output: *mut VECTOR,
        count: ::core::ffi::c_int,
        vertices: *mut VECTOR,
        local_screen: *mut f32,
    );
}
#[repr(C, packed(8))]
#[derive(Copy, Clone)]
pub union xyz_t {
    pub xyz: u64_,
    pub __bindgen_anon_1: xyz_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xyz_t__bindgen_ty_1 {
    pub x: u16_,
    pub y: u16_,
    pub z: u32_,
}
#[repr(C, packed(8))]
#[derive(Copy, Clone)]
pub union texel_t {
    pub uv: u64_,
    pub __bindgen_anon_1: texel_t__bindgen_ty_1,
    pub __bindgen_anon_2: texel_t__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct texel_t__bindgen_ty_1 {
    pub s: f32,
    pub t: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct texel_t__bindgen_ty_2 {
    pub u: f32,
    pub v: f32,
}
#[repr(C, packed(8))]
#[derive(Copy, Clone)]
pub union color_t {
    pub rgbaq: u64_,
    pub __bindgen_anon_1: color_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct color_t__bindgen_ty_1 {
    pub r: u8_,
    pub g: u8_,
    pub b: u8_,
    pub a: u8_,
    pub q: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vertex_t {
    pub x: f32,
    pub y: f32,
    pub z: ::core::ffi::c_uint,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union texel_f_t {
    pub strq: VECTOR,
    pub __bindgen_anon_1: texel_f_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct texel_f_t__bindgen_ty_1 {
    pub s: f32,
    pub t: f32,
    pub r: f32,
    pub q: f32,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union color_f_t {
    pub rgba: VECTOR,
    pub __bindgen_anon_1: color_f_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct color_f_t__bindgen_ty_1 {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union vertex_f_t {
    pub xyzw: VECTOR,
    pub __bindgen_anon_1: vertex_f_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vertex_f_t__bindgen_ty_1 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct point_t {
    pub v0: vertex_t,
    pub color: color_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct line_t {
    pub v0: vertex_t,
    pub v1: vertex_t,
    pub color: color_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct triangle_t {
    pub v0: vertex_t,
    pub v1: vertex_t,
    pub v2: vertex_t,
    pub color: color_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rect_t {
    pub v0: vertex_t,
    pub v1: vertex_t,
    pub color: color_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct texrect_t {
    pub v0: vertex_t,
    pub t0: texel_t,
    pub v1: vertex_t,
    pub t1: texel_t,
    pub color: color_t,
}
unsafe extern "C" {
    #[doc = " Enables alpha blending"]
    pub fn draw_enable_blending();
}
unsafe extern "C" {
    #[doc = " Disables alpha blending"]
    pub fn draw_disable_blending();
}
unsafe extern "C" {
    #[doc = " Draws a single point"]
    pub fn draw_point(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        point: *mut point_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws a single line"]
    pub fn draw_line(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        line: *mut line_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws a triangle using a line strip"]
    pub fn draw_triangle_outline(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        triangle: *mut triangle_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws a single triangle"]
    pub fn draw_triangle_filled(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        triangle: *mut triangle_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws a rectangle using line primitives"]
    pub fn draw_rect_outline(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        rect: *mut rect_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws a single sprite"]
    pub fn draw_rect_filled(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        rect: *mut rect_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws a single texture mapped sprite"]
    pub fn draw_rect_textured(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        rect: *mut texrect_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws multiple sprite primitives"]
    pub fn draw_rect_filled_strips(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        rect: *mut rect_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws multiple strips to render a large texture\n width must be multiple of 32 - 0.9375"]
    pub fn draw_rect_textured_strips(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        rect: *mut texrect_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws filled round rectangle, buggy with partial coordinates"]
    pub fn draw_round_rect_filled(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        rect: *mut rect_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws a hollow round rectangle, buggy with partial coordinates"]
    pub fn draw_round_rect_outline(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        rect: *mut rect_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws an arc using line primitives"]
    pub fn draw_arc_outline(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        center: *mut point_t,
        radius: f32,
        angle_start: f32,
        angle_end: f32,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Draws multiple triangle fans"]
    pub fn draw_arc_filled(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        center: *mut point_t,
        radius: f32,
        angle_start: f32,
        angle_end: f32,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Begins a primitive, allowing for vertex data to be filled in the packet directly"]
    pub fn draw_prim_start(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        prim: *mut prim_t,
        color: *mut color_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Ends a primitive by calculating the number of qwords used, the number of registers, the register list"]
    pub fn draw_prim_end(q: *mut qword_t, nreg: ::core::ffi::c_int, reglist: u64_) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Converts floating point color, replacing alpha with constant value, and calculates q"]
    pub fn draw_convert_rgbq(
        output: *mut color_t,
        count: ::core::ffi::c_int,
        vertices: *mut vertex_f_t,
        colours: *mut color_f_t,
        alpha: ::core::ffi::c_uchar,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Converts floating point color and calculates q value"]
    pub fn draw_convert_rgbaq(
        output: *mut color_t,
        count: ::core::ffi::c_int,
        vertices: *mut vertex_f_t,
        colours: *mut color_f_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Calculates the st coordinates from the perspective coordinate q = 1/w"]
    pub fn draw_convert_st(
        output: *mut texel_t,
        count: ::core::ffi::c_int,
        vertices: *mut vertex_f_t,
        coords: *mut texel_f_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Converts and translates floating point vertices to fixed point vertices"]
    pub fn draw_convert_xyz(
        output: *mut xyz_t,
        x: f32,
        y: f32,
        z: ::core::ffi::c_int,
        count: ::core::ffi::c_int,
        vertices: *mut vertex_f_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Sets up the drawing environment based on the framebuffer and zbuffer settings"]
    pub fn draw_setup_environment(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        frame: *mut framebuffer_t,
        z: *mut zbuffer_t,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Clear the screen based on the screen's origin, width, and height using the defined color."]
    pub fn draw_clear(
        q: *mut qword_t,
        context: ::core::ffi::c_int,
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        r: ::core::ffi::c_int,
        g: ::core::ffi::c_int,
        b: ::core::ffi::c_int,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Signal that drawing is finished"]
    pub fn draw_finish(q: *mut qword_t) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Wait until finish event occurs"]
    pub fn draw_wait_finish();
}
unsafe extern "C" {
    #[doc = " Creates a dma chain filled with image information"]
    pub fn draw_texture_transfer(
        q: *mut qword_t,
        src: *mut ::core::ffi::c_void,
        width: ::core::ffi::c_int,
        height: ::core::ffi::c_int,
        psm: ::core::ffi::c_int,
        dest: ::core::ffi::c_int,
        dest_width: ::core::ffi::c_int,
    ) -> *mut qword_t;
}
unsafe extern "C" {
    #[doc = " Flush the texture cache"]
    pub fn draw_texture_flush(q: *mut qword_t) -> *mut qword_t;
}
pub const Packet2Mode_P2_MODE_NORMAL: Packet2Mode = 0;
pub const Packet2Mode_P2_MODE_CHAIN: Packet2Mode = 1;
#[doc = " Two modes are commonly used with the DMA Controller (DMAC): normal mode and\n chain mode. In normal mode, transfers are issued one at a time. In chain mode, a\n series of transfers are issued simultaneously by initiating a transfer that contains\n \"DMA Tags\", which in turn contains instructions for further transfers. You will\n probably use chain mode for the majority of your transfers."]
pub type Packet2Mode = ::core::ffi::c_uint;
#[doc = " Normal."]
pub const Packet2Type_P2_TYPE_NORMAL: Packet2Type = 0;
#[doc = " Uncached."]
pub const Packet2Type_P2_TYPE_UNCACHED: Packet2Type = 536870912;
#[doc = " Uncached accelerated."]
pub const Packet2Type_P2_TYPE_UNCACHED_ACCL: Packet2Type = 805306368;
#[doc = " Scratchpad memory."]
pub const Packet2Type_P2_TYPE_SPRAM: Packet2Type = 1879048192;
#[doc = " Types of memory mapping."]
pub type Packet2Type = ::core::ffi::c_uint;
#[doc = " Transfers the QWC qword from the ADDR field, clears the Dn_CHCR.STR to 0, and ends transfer."]
pub const DmaTagType_P2_DMA_TAG_REFE: DmaTagType = 0;
#[doc = " Transfers the QWC qword following the tag and reads the succeeding qword as the next tag."]
pub const DmaTagType_P2_DMA_TAG_CNT: DmaTagType = 1;
#[doc = " Transfers the QWC qword following the tag and reads the qword of the ADDR field as the next tag."]
pub const DmaTagType_P2_DMA_TAG_NEXT: DmaTagType = 2;
#[doc = " Transfers the QWC qword from the ADDR field and reads the qword following the tag as the next tag."]
pub const DmaTagType_P2_DMA_TAG_REF: DmaTagType = 3;
#[doc = " Transfers the QWC qword from the ADDR field while controlling stalls\n and reads the qword following the tag as the next tag.\n @note Effective only on the VIF1, GIF, and SIF1 channels."]
pub const DmaTagType_P2_DMA_TAG_REFS: DmaTagType = 4;
#[doc = " Transfers the QWC qword following the tag, pushes the next field into\n the Dn_ASR register, and reads the qword of the ADDR field as the next tag.\n @note Effective only on the VIF0, VIF1, and GIF channels.\n Addresses can be pushed up to 2 levels"]
pub const DmaTagType_P2_DMA_TAG_CALL: DmaTagType = 5;
#[doc = " Transfers the QWC qword following the tag and reads the\n qword of the field popped from the Dn_ASR register as the\n next tag.\n Transfers the QWC qword following the tag, clears the\n Dn_CHCR.STR to 0, and ends transfer when there is no\n pushed address.\n @note Effective only on the VIF0, VIF1, and GIF channels."]
pub const DmaTagType_P2_DMA_TAG_RET: DmaTagType = 6;
#[doc = " Transfers the QWC qword following the tag, clears the Dn_CHCR.STR to 0, and ends transfer."]
pub const DmaTagType_P2_DMA_TAG_END: DmaTagType = 7;
#[doc = " DMA tag types"]
pub type DmaTagType = ::core::ffi::c_uint;
#[doc = " Destination chain tag."]
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct dma_tag_t {
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 8usize]>,
    pub OPT1: u32_,
    pub OPT2: u32_,
}
impl dma_tag_t {
    #[inline]
    pub fn QWC(&self) -> u64_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 16u8) as u64) }
    }
    #[inline]
    pub fn set_QWC(&mut self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 16u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn QWC_raw(this: *const Self) -> u64_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                16u8,
            ) as u64)
        }
    }
    #[inline]
    pub unsafe fn set_QWC_raw(this: *mut Self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                16u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn PAD(&self) -> u64_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(16usize, 10u8) as u64) }
    }
    #[inline]
    pub fn set_PAD(&mut self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set(16usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn PAD_raw(this: *const Self) -> u64_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                16usize,
                10u8,
            ) as u64)
        }
    }
    #[inline]
    pub unsafe fn set_PAD_raw(this: *mut Self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                16usize,
                10u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn PCE(&self) -> u64_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(26usize, 2u8) as u64) }
    }
    #[inline]
    pub fn set_PCE(&mut self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set(26usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn PCE_raw(this: *const Self) -> u64_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                26usize,
                2u8,
            ) as u64)
        }
    }
    #[inline]
    pub unsafe fn set_PCE_raw(this: *mut Self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                26usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn ID(&self) -> u64_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(28usize, 3u8) as u64) }
    }
    #[inline]
    pub fn set_ID(&mut self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set(28usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn ID_raw(this: *const Self) -> u64_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                28usize,
                3u8,
            ) as u64)
        }
    }
    #[inline]
    pub unsafe fn set_ID_raw(this: *mut Self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                28usize,
                3u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn IRQ(&self) -> u64_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(31usize, 1u8) as u64) }
    }
    #[inline]
    pub fn set_IRQ(&mut self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set(31usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn IRQ_raw(this: *const Self) -> u64_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                31usize,
                1u8,
            ) as u64)
        }
    }
    #[inline]
    pub unsafe fn set_IRQ_raw(this: *mut Self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                31usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn ADDR(&self) -> u64_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(32usize, 31u8) as u64) }
    }
    #[inline]
    pub fn set_ADDR(&mut self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set(32usize, 31u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn ADDR_raw(this: *const Self) -> u64_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                32usize,
                31u8,
            ) as u64)
        }
    }
    #[inline]
    pub unsafe fn set_ADDR_raw(this: *mut Self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                32usize,
                31u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn SPR(&self) -> u64_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(63usize, 1u8) as u64) }
    }
    #[inline]
    pub fn set_SPR(&mut self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set(63usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn SPR_raw(this: *const Self) -> u64_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                63usize,
                1u8,
            ) as u64)
        }
    }
    #[inline]
    pub unsafe fn set_SPR_raw(this: *mut Self, val: u64_) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                63usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        QWC: u64_,
        PAD: u64_,
        PCE: u64_,
        ID: u64_,
        IRQ: u64_,
        ADDR: u64_,
        SPR: u64_,
    ) -> __BindgenBitfieldUnit<[u8; 8usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 8usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 16u8, {
            let QWC: u64 = unsafe { ::core::mem::transmute(QWC) };
            QWC as u64
        });
        __bindgen_bitfield_unit.set(16usize, 10u8, {
            let PAD: u64 = unsafe { ::core::mem::transmute(PAD) };
            PAD as u64
        });
        __bindgen_bitfield_unit.set(26usize, 2u8, {
            let PCE: u64 = unsafe { ::core::mem::transmute(PCE) };
            PCE as u64
        });
        __bindgen_bitfield_unit.set(28usize, 3u8, {
            let ID: u64 = unsafe { ::core::mem::transmute(ID) };
            ID as u64
        });
        __bindgen_bitfield_unit.set(31usize, 1u8, {
            let IRQ: u64 = unsafe { ::core::mem::transmute(IRQ) };
            IRQ as u64
        });
        __bindgen_bitfield_unit.set(32usize, 31u8, {
            let ADDR: u64 = unsafe { ::core::mem::transmute(ADDR) };
            ADDR as u64
        });
        __bindgen_bitfield_unit.set(63usize, 1u8, {
            let SPR: u64 = unsafe { ::core::mem::transmute(SPR) };
            SPR as u64
        });
        __bindgen_bitfield_unit
    }
}
pub const UnpackMode_P2_UNPACK_S_32: UnpackMode = 0;
pub const UnpackMode_P2_UNPACK_S_16: UnpackMode = 1;
pub const UnpackMode_P2_UNPACK_S_8: UnpackMode = 2;
pub const UnpackMode_P2_UNPACK_V2_32: UnpackMode = 4;
pub const UnpackMode_P2_UNPACK_V2_16: UnpackMode = 5;
pub const UnpackMode_P2_UNPACK_V2_8: UnpackMode = 6;
pub const UnpackMode_P2_UNPACK_V3_32: UnpackMode = 8;
pub const UnpackMode_P2_UNPACK_V3_16: UnpackMode = 9;
pub const UnpackMode_P2_UNPACK_V3_8: UnpackMode = 10;
pub const UnpackMode_P2_UNPACK_V4_32: UnpackMode = 12;
pub const UnpackMode_P2_UNPACK_V4_16: UnpackMode = 13;
pub const UnpackMode_P2_UNPACK_V4_8: UnpackMode = 14;
pub const UnpackMode_P2_UNPACK_V4_5: UnpackMode = 15;
#[doc = " Unpack modes.\n V2 = 2 dimensions, S = Single = 1 dimension\n _32 = 32 bits of data length."]
pub type UnpackMode = ::core::ffi::c_uint;
#[doc = " No operation.\n No operation is performed.\n NOP is used to adjust the data alignment in the VIF packet."]
pub const VIFOpcode_P2_VIF_NOP: VIFOpcode = 0;
#[doc = " Sets write recycle.\n STCYCL writes the value of the IMMEDIATE field to the VIFn_CYCLE register."]
pub const VIFOpcode_P2_VIF_STCYCL: VIFOpcode = 1;
#[doc = " Sets the double buffer offset.\n OFFSET writes the lower 10 bits of the IMMEDIATE field to the VIF1_OFST register.\n At the same time, the DBF flag of the VIF1_STAT register is cleared to 0, and the VIF1_BASE register\n value is set to the VIF1_TOPS. That is, the pointer for the double buffer points to the BASE."]
pub const VIFOpcode_P2_VIF_OFFSET: VIFOpcode = 2;
#[doc = " Sets the base address of the double buffer.\n BASE writes the lower 10 bits of the IMMEDIATE field to the VIF1_BASE register.\n These bits become the base address of the double buffers."]
pub const VIFOpcode_P2_VIF_BASE: VIFOpcode = 3;
#[doc = " Sets the data pointer.\n ITOP writes the lower 10 bits of the IMMEDIATE field to the VIFn_ITOPS register.\n This value is read from the VU by the XITOP instruction."]
pub const VIFOpcode_P2_VIF_ITOP: VIFOpcode = 4;
#[doc = " Sets the addition decompression mode.\n STMOD writes the lower 2 bits of the IMMEDIATE field to the VIFn_MODE register.\n This becomes the addition decompression mode setting."]
pub const VIFOpcode_P2_VIF_STMOD: VIFOpcode = 5;
#[doc = " Sets the PATH3 mask.\n MSKPATH3 enables/disables transfer processing via the GIF PATH3.\n The setting of this register applies to the next data block or later."]
pub const VIFOpcode_P2_VIF_MSKPATH3: VIFOpcode = 6;
#[doc = " Sets the MARK value.\n MARK writes the value of the IMMEDIATE field to the VIFn_MARK register.\n By properly setting the MARK value, it becomes possible to use this value for\n synchronization with the EE Core and debugging."]
pub const VIFOpcode_P2_VIF_MARK: VIFOpcode = 7;
#[doc = " Waits for end of the microprogram.\n FLUSHE waits for the state in which the microprogram in VU0/VU1 has been ended."]
pub const VIFOpcode_P2_VIF_FLUSHE: VIFOpcode = 16;
#[doc = " Waits for end of the microprogram.\n FLUSH waits for the state in which transfers to the GIF from PATH1 and PATH2 have been ended after\n end of microprogram in VU1. FLUSH does not wait for the end of the transfer via PATH1 by\n the XGKICK instruction with the E bit."]
pub const VIFOpcode_P2_VIF_FLUSH: VIFOpcode = 17;
#[doc = " Waits for end of the microprogram.\n FLUSHA waits for the state in which there is no transfer request from PATH3 after the end of micro\n program in VU1 and end of transfer to the GIF from PATH1 and PATH2."]
pub const VIFOpcode_P2_VIF_FLUSHA: VIFOpcode = 19;
#[doc = " Activates the microprogram.\n MSCAL waits for the end of the microprogram under execution and activates the micro program with the\n value of the IMMEDIATE field as the starting address."]
pub const VIFOpcode_P2_VIF_MSCAL: VIFOpcode = 20;
#[doc = " Activates the microprogram.\n MSCNT waits for the end of the microprogram under execution and executes the next microprogram from\n the address following the most recently ended one in the PC (program counter)."]
pub const VIFOpcode_P2_VIF_MSCNT: VIFOpcode = 23;
#[doc = " Activates the microprogram.\n MSCALF waits for the end of both the microprogram and the GIF(PATH1/PATH2) transfer and executes\n the microprogram with the value of the IMMEDIATE field as the starting address."]
pub const VIFOpcode_P2_VIF_MSCALF: VIFOpcode = 21;
#[doc = " Sets the data mask pattern.\n STMASK stores the next 1 word of data in the VIFn_MASK register.\n This data becomes the mask pattern of the write data."]
pub const VIFOpcode_P2_VIF_STMASK: VIFOpcode = 32;
#[doc = " Sets the filling data.\n STROW stores the following 4 words of data in the VIFn_R0 - VIFn_R3 registers.\n These are used as filling data when decompressed by the VIFcode UNPACK."]
pub const VIFOpcode_P2_VIF_STROW: VIFOpcode = 48;
#[doc = " Sets the filling data.\n STCOL stores the following 4 words of data in the VIFn_C0 - VIFn_C3 registers.\n These are used as filling data when decompressed by the VIFcode UNPACK."]
pub const VIFOpcode_P2_VIF_STCOL: VIFOpcode = 49;
#[doc = " Transfers the microprogram.\n MPG waits for the end of the microprogram and transfers the following NUM pieces of 64-bit data.\n (microinstruction code) to the MicroMem address shown by the IMMEDIATE field."]
pub const VIFOpcode_P2_VIF_MPG: VIFOpcode = 74;
#[doc = " Transfers data to the GIF(GS).\n DIRECT transfers the following IMMEDIATE pieces of 128-bit data to the GS via GIF PATH2. It is\n necessary to put the appropriate GIFtag to the data."]
pub const VIFOpcode_P2_VIF_DIRECT: VIFOpcode = 80;
#[doc = " Transfers data to the GIF(GS).\n DIRECTHL transfers the following IMMEDIATE pieces of 128-bit data to the GS via GIF PATH2.\n The appropriate GIFtag must be attached to the data.\n Interruption of PATH3 IMAGE mode data does not occur during the data transfer via PATH2 by\n DIRECTHL. Moreover, when the IMAGE mode data is being transferred via PATH3, DIRECTHL stalls\n until the end of the transfer."]
pub const VIFOpcode_P2_VIF_DIRECTHL: VIFOpcode = 81;
#[doc = " VIF opcodes."]
pub type VIFOpcode = ::core::ffi::c_uint;
#[doc = " VIFCode structure."]
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct vif_code_t {
    pub _bitfield_align_1: [u16; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
}
impl vif_code_t {
    #[inline]
    pub fn immediate(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 16u8) as u32) }
    }
    #[inline]
    pub fn set_immediate(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 16u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn immediate_raw(this: *const Self) -> u32_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                16u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_immediate_raw(this: *mut Self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                16u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn num(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(16usize, 8u8) as u32) }
    }
    #[inline]
    pub fn set_num(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(16usize, 8u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn num_raw(this: *const Self) -> u32_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                16usize,
                8u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_num_raw(this: *mut Self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                16usize,
                8u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn cmd(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(24usize, 8u8) as u32) }
    }
    #[inline]
    pub fn set_cmd(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(24usize, 8u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn cmd_raw(this: *const Self) -> u32_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                24usize,
                8u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_cmd_raw(this: *mut Self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                24usize,
                8u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        immediate: u32_,
        num: u32_,
        cmd: u32_,
    ) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 16u8, {
            let immediate: u32 = unsafe { ::core::mem::transmute(immediate) };
            immediate as u64
        });
        __bindgen_bitfield_unit.set(16usize, 8u8, {
            let num: u32 = unsafe { ::core::mem::transmute(num) };
            num as u64
        });
        __bindgen_bitfield_unit.set(24usize, 8u8, {
            let cmd: u32 = unsafe { ::core::mem::transmute(cmd) };
            cmd as u64
        });
        __bindgen_bitfield_unit
    }
}
#[doc = " DMA data packet.\n Successor of standard packet."]
#[repr(C)]
#[repr(align(64))]
#[derive(Debug, Copy, Clone)]
pub struct packet2_t {
    #[doc = " Maximum number of qwords which was defined in packet2_create()."]
    pub max_qwords_count: u16_,
    #[doc = " Type of packet's memory mapping."]
    pub type_: Packet2Type,
    #[doc = " Packet mode."]
    pub mode: Packet2Mode,
    #[doc = " Tag transfer enable.\n Effective only in chain mode.\n If >0 transfer tag is set during packet sending and\n add_dma_tag() (so also every open_tag()) will move buffer by DWORD,\n so remember to align memory!"]
    pub tte: u8_,
    pub __bindgen_padding_0: [u64; 6usize],
    #[doc = " Start position of the buffer."]
    pub base: *mut qword_t,
    #[doc = " Current position of the buffer."]
    pub next: *mut qword_t,
    #[doc = " The buffer position where DMA tag was opened.\n NULL, if no dma tag is open."]
    pub tag_opened_at: *mut dma_tag_t,
    #[doc = " The buffer position where DIRECT/UNPACK was opened.\n NULL, if no DIRECT/UNPACK is open."]
    pub vif_code_opened_at: *mut vif_code_t,
}
#[doc = " Mask, used in VIF's STMASK opcode."]
#[repr(C)]
#[derive(Copy, Clone)]
pub union Mask {
    pub __bindgen_anon_1: Mask__bindgen_ty_1,
    pub m: ::core::ffi::c_uint,
}
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct Mask__bindgen_ty_1 {
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
}
impl Mask__bindgen_ty_1 {
    #[inline]
    pub fn m0(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m0(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m0_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m0_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m1(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(2usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m1(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(2usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m1_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                2usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m1_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                2usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m2(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(4usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m2(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(4usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m2_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                4usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m2_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                4usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m3(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(6usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m3(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(6usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m3_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                6usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m3_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                6usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m4(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(8usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m4(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(8usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m4_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                8usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m4_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                8usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m5(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(10usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m5(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(10usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m5_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                10usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m5_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                10usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m6(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(12usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m6(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(12usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m6_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                12usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m6_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                12usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m7(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(14usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m7(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(14usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m7_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                14usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m7_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                14usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m8(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(16usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m8(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(16usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m8_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                16usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m8_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                16usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m9(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(18usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m9(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(18usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m9_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                18usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m9_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                18usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m10(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(20usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m10(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(20usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m10_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                20usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m10_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                20usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m11(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(22usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m11(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(22usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m11_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                22usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m11_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                22usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m12(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(24usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m12(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(24usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m12_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                24usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m12_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                24usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m13(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(26usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m13(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(26usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m13_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                26usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m13_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                26usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m14(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(28usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m14(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(28usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m14_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                28usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m14_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                28usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn m15(&self) -> ::core::ffi::c_uint {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(30usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_m15(&mut self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(30usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn m15_raw(this: *const Self) -> ::core::ffi::c_uint {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                30usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_m15_raw(this: *mut Self, val: ::core::ffi::c_uint) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                30usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        m0: ::core::ffi::c_uint,
        m1: ::core::ffi::c_uint,
        m2: ::core::ffi::c_uint,
        m3: ::core::ffi::c_uint,
        m4: ::core::ffi::c_uint,
        m5: ::core::ffi::c_uint,
        m6: ::core::ffi::c_uint,
        m7: ::core::ffi::c_uint,
        m8: ::core::ffi::c_uint,
        m9: ::core::ffi::c_uint,
        m10: ::core::ffi::c_uint,
        m11: ::core::ffi::c_uint,
        m12: ::core::ffi::c_uint,
        m13: ::core::ffi::c_uint,
        m14: ::core::ffi::c_uint,
        m15: ::core::ffi::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 2u8, {
            let m0: u32 = unsafe { ::core::mem::transmute(m0) };
            m0 as u64
        });
        __bindgen_bitfield_unit.set(2usize, 2u8, {
            let m1: u32 = unsafe { ::core::mem::transmute(m1) };
            m1 as u64
        });
        __bindgen_bitfield_unit.set(4usize, 2u8, {
            let m2: u32 = unsafe { ::core::mem::transmute(m2) };
            m2 as u64
        });
        __bindgen_bitfield_unit.set(6usize, 2u8, {
            let m3: u32 = unsafe { ::core::mem::transmute(m3) };
            m3 as u64
        });
        __bindgen_bitfield_unit.set(8usize, 2u8, {
            let m4: u32 = unsafe { ::core::mem::transmute(m4) };
            m4 as u64
        });
        __bindgen_bitfield_unit.set(10usize, 2u8, {
            let m5: u32 = unsafe { ::core::mem::transmute(m5) };
            m5 as u64
        });
        __bindgen_bitfield_unit.set(12usize, 2u8, {
            let m6: u32 = unsafe { ::core::mem::transmute(m6) };
            m6 as u64
        });
        __bindgen_bitfield_unit.set(14usize, 2u8, {
            let m7: u32 = unsafe { ::core::mem::transmute(m7) };
            m7 as u64
        });
        __bindgen_bitfield_unit.set(16usize, 2u8, {
            let m8: u32 = unsafe { ::core::mem::transmute(m8) };
            m8 as u64
        });
        __bindgen_bitfield_unit.set(18usize, 2u8, {
            let m9: u32 = unsafe { ::core::mem::transmute(m9) };
            m9 as u64
        });
        __bindgen_bitfield_unit.set(20usize, 2u8, {
            let m10: u32 = unsafe { ::core::mem::transmute(m10) };
            m10 as u64
        });
        __bindgen_bitfield_unit.set(22usize, 2u8, {
            let m11: u32 = unsafe { ::core::mem::transmute(m11) };
            m11 as u64
        });
        __bindgen_bitfield_unit.set(24usize, 2u8, {
            let m12: u32 = unsafe { ::core::mem::transmute(m12) };
            m12 as u64
        });
        __bindgen_bitfield_unit.set(26usize, 2u8, {
            let m13: u32 = unsafe { ::core::mem::transmute(m13) };
            m13 as u64
        });
        __bindgen_bitfield_unit.set(28usize, 2u8, {
            let m14: u32 = unsafe { ::core::mem::transmute(m14) };
            m14 as u64
        });
        __bindgen_bitfield_unit.set(30usize, 2u8, {
            let m15: u32 = unsafe { ::core::mem::transmute(m15) };
            m15 as u64
        });
        __bindgen_bitfield_unit
    }
}
unsafe extern "C" {
    #[doc = " Allocate new packet2.\n @param qwords Maximum data size in qwords (128bit).\n @param type Memory mapping type.\n @param mode Packet mode. Normal or chain.\n @param tte Tag transfer enable.\n Used only for CHAIN mode!\n If >0 transfer tag is set during packet sending and\n add_dma_tag() (so also every open_tag()) will move buffer by DWORD,\n so remember to align memory!\n @returns Pointer to packet2 on success or NULL if memory allocation fail."]
    pub fn packet2_create(
        qwords: u16_,
        type_: Packet2Type,
        mode: Packet2Mode,
        tte: u8_,
    ) -> *mut packet2_t;
}
unsafe extern "C" {
    #[doc = " Create new packet2 with given data pointer.\n @param base Pointer to base (start of buffer).\n @param next Pointer to next (current position of buffer).\n @param qwords Maximum data size in qwords (128bit).\n @param type Memory mapping type.\n @param mode Packet mode. Normal or chain (so also vif/vu).\n @param tte Tag transfer enable.\n Used only for CHAIN mode!\n If >0 transfer tag is set during packet sending and\n add_dma_tag() (so also every open_tag()) will move buffer by DWORD,\n so remember to align memory!\n @returns Pointer to packet2 on success or NULL if memory allocation fail."]
    pub fn packet2_create_from(
        base: *mut qword_t,
        next: *mut qword_t,
        qwords: u16_,
        type_: Packet2Type,
        mode: Packet2Mode,
        tte: u8_,
    ) -> *mut packet2_t;
}
unsafe extern "C" {
    #[doc = " Free packet2 memory.\n @param packet2 Pointer to packet2."]
    pub fn packet2_free(packet2: *mut packet2_t);
}
unsafe extern "C" {
    #[doc = " Reset packet.\n Move next pointer back to base pointer,\n Make all \"openedAt\" vars to NULL\n Do memset on data if required.\n @param packet2 Pointer to packet.\n @param clear_mem If >0, data is cleared via memset(). SLOW!"]
    pub fn packet2_reset(packet2: *mut packet2_t, clear_mem: u8_);
}
unsafe extern "C" {
    #[doc = " Print data of packet.\n @param packet2 Pointer to packet.\n @param clear_mem Count of qwords, type 0 for all."]
    pub fn packet2_print(packet2: *mut packet2_t, qw_count: u32_);
}
unsafe extern "C" {
    #[doc = " Print amount of qwords of packet.\n @param packet2 Pointer to packet."]
    pub fn packet2_print_qw_count(packet2: *mut packet2_t);
}
unsafe extern "C" {
    #[doc = " Copy data from b packet into a packet with memcpy()"]
    pub fn packet2_add(a: *mut packet2_t, b: *mut packet2_t);
}
unsafe extern "C" {
    pub fn __assert(
        arg1: *const ::core::ffi::c_char,
        arg2: ::core::ffi::c_int,
        arg3: *const ::core::ffi::c_char,
    ) -> !;
}
unsafe extern "C" {
    pub fn __assert_func(
        arg1: *const ::core::ffi::c_char,
        arg2: ::core::ffi::c_int,
        arg3: *const ::core::ffi::c_char,
        arg4: *const ::core::ffi::c_char,
    ) -> !;
}
