/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub const SIF_DMA_INT_I: u32 = 2;
pub const SIF_DMA_INT_O: u32 = 4;
pub const SIF_DMA_ERT: u32 = 64;
pub const SIF_REG_ID_SYSTEM: u32 = 2147483648;
pub const SIF_STAT_SIFINIT: u32 = 65536;
pub const SIF_STAT_CMDINIT: u32 = 131072;
pub const SIF_STAT_BOOTEND: u32 = 262144;
pub const TH_SELF: u32 = 0;
pub const MAX_THREADS: u32 = 256;
pub const MAX_SEMAPHORES: u32 = 256;
pub const MAX_PRIORITY: u32 = 128;
pub const MAX_HANDLERS: u32 = 128;
pub const MAX_ALARMS: u32 = 64;
pub const WRITEBACK_DCACHE: u32 = 0;
pub const INVALIDATE_DCACHE: u32 = 1;
pub const INVALIDATE_ICACHE: u32 = 2;
pub const INVALIDATE_CACHE: u32 = 3;
pub const INIT_DMAC: u32 = 1;
pub const INIT_VU1: u32 = 2;
pub const INIT_VIF1: u32 = 4;
pub const INIT_GIF: u32 = 8;
pub const INIT_VU0: u32 = 16;
pub const INIT_VIF0: u32 = 32;
pub const INIT_IPU: u32 = 64;
pub const THS_RUN: u32 = 1;
pub const THS_READY: u32 = 2;
pub const THS_WAIT: u32 = 4;
pub const THS_SUSPEND: u32 = 8;
pub const THS_WAITSUSPEND: u32 = 12;
pub const THS_DORMANT: u32 = 16;
pub const TSW_NONE: u32 = 0;
pub const TSW_SLEEP: u32 = 1;
pub const TSW_SEMA: u32 = 2;
pub const CPU_DATA_CACHE: u32 = 1;
pub const CPU_INSTRUCTION_CACHE: u32 = 2;
pub const SIF_CMD_ID_SYSTEM: u32 = 2147483648;
pub const SIF_CMD_CHANGE_SADDR: u32 = 2147483648;
pub const SIF_CMD_SET_SREG: u32 = 2147483649;
pub const SIF_CMD_INIT_CMD: u32 = 2147483650;
pub const SIF_CMD_RESET_CMD: u32 = 2147483651;
pub const SIF_CMD_RPC_END: u32 = 2147483656;
pub const SIF_CMD_RPC_BIND: u32 = 2147483657;
pub const SIF_CMD_RPC_CALL: u32 = 2147483658;
pub const SIF_CMD_RPC_RDATA: u32 = 2147483660;
pub const SIF_SREG_RPCINIT: u32 = 0;
pub const RESET_ARG_MAX: u32 = 79;
pub const SIF_CMD_M_INTR: u32 = 1;
pub const SIF_CMD_M_WBDC: u32 = 4;
pub const LF_PATH_MAX: u32 = 252;
pub const LF_ARG_MAX: u32 = 252;
pub const SCE_EBINDMISS: u32 = 65536;
pub const SCE_ECALLMISS: u32 = 65537;
pub const SCE_ELOADMISS: u32 = 65539;
pub type u8_ = ::core::ffi::c_uchar;
pub type u16_ = ::core::ffi::c_ushort;
pub type u32_ = ::core::ffi::c_uint;
pub type u64_ = ::core::ffi::c_ulonglong;
pub type u128_ = u128;
pub type s8 = ::core::ffi::c_schar;
pub type s16 = ::core::ffi::c_short;
pub type vs8 = s8;
pub type vs16 = s16;
pub type s32 = ::core::ffi::c_int;
pub type s64 = ::core::ffi::c_longlong;
pub type s128 = i128;
pub type vs32 = s32;
pub type vs64 = s64;
pub type vs128 = i128;
pub type uiptr = u32_;
pub type siptr = s32;
pub type vuiptr = u32_;
pub type vsiptr = s32;
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union qword_t {
    pub qw: u128_,
    pub b: [u8_; 16usize],
    pub hw: [u16_; 8usize],
    pub sw: [u32_; 4usize],
    pub dw: [u64_; 2usize],
}
pub type wchar_t = ::core::ffi::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::core::ffi::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
pub type __gnuc_va_list = __builtin_va_list;
pub type va_list = __builtin_va_list;
#[doc = " Main -> sub-CPU command buffer (MSCOM)"]
pub const _sif_regs_SIF_REG_MAINADDR: _sif_regs = 1;
#[doc = " Sub -> main-CPU command buffer (SMCOM)"]
pub const _sif_regs_SIF_REG_SUBADDR: _sif_regs = 2;
#[doc = " Main -> sub-CPU flag (MSFLAG)"]
pub const _sif_regs_SIF_REG_MSFLAG: _sif_regs = 3;
#[doc = " Sub -> main-CPU flag (SMFLAG)"]
pub const _sif_regs_SIF_REG_SMFLAG: _sif_regs = 4;
#[doc = " Sub -> main-CPU flag (SMFLAG)"]
pub const _sif_regs_SIF_SYSREG_SUBADDR: _sif_regs = 2147483648;
#[doc = " Sub -> main-CPU flag (SMFLAG)"]
pub const _sif_regs_SIF_SYSREG_MAINADDR: _sif_regs = 2147483649;
#[doc = " Sub -> main-CPU flag (SMFLAG)"]
pub const _sif_regs_SIF_SYSREG_RPCINIT: _sif_regs = 2147483650;
pub type _sif_regs = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_SifDmaTransfer {
    pub src: *mut ::core::ffi::c_void,
    pub dest: *mut ::core::ffi::c_void,
    pub size: ::core::ffi::c_int,
    pub attr: ::core::ffi::c_int,
}
pub type SifDmaTransfer_t = t_SifDmaTransfer;
unsafe extern "C" {
    pub fn sceSifDmaStat(trid: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn sceSifSetDma(
        dmat: *mut SifDmaTransfer_t,
        count: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
#[doc = " Programmable register to select TLB entry for reading or writing (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_Index: mips_cop0_reg = 0;
#[doc = " Pseudo-random counter for TLB replacement (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_Random: mips_cop0_reg = 1;
#[doc = " Low half of TLB entry for even PFN (Physical page number) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_EntryLo0: mips_cop0_reg = 2;
#[doc = " Low half of TLB entry for odd PFN (Physical page number) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_EntryLo1: mips_cop0_reg = 3;
#[doc = " Pointer to kernel virtual PTE table (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Context: mips_cop0_reg = 4;
#[doc = " Mask that sets the TLB page size (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_PageMask: mips_cop0_reg = 5;
#[doc = " Number of wired TLB entries (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_Wired: mips_cop0_reg = 6;
#[doc = " Bad virtual address (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_BadVAddr: mips_cop0_reg = 8;
#[doc = " Timer compare (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Count: mips_cop0_reg = 9;
#[doc = " High half of TLB entry(Virtual page number and ASID) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_EntryHi: mips_cop0_reg = 10;
#[doc = " Timer compare (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Compare: mips_cop0_reg = 11;
#[doc = " Processor Status Register (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Status: mips_cop0_reg = 12;
#[doc = " Cause of the last exception taken (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Cause: mips_cop0_reg = 13;
#[doc = " Exception Program Counter (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_EPC: mips_cop0_reg = 14;
#[doc = " Processor Revision Identifier (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_PRId: mips_cop0_reg = 15;
#[doc = " Configuration Register (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_Config: mips_cop0_reg = 16;
#[doc = " Bad Physical Address (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_BadPAddr: mips_cop0_reg = 23;
#[doc = " This is used for Debug function (purpose: Debug)"]
pub const mips_cop0_reg_COP0_REG_Debug: mips_cop0_reg = 24;
#[doc = " Performance Counter and Control Register (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Perf: mips_cop0_reg = 25;
#[doc = " Cache Tag register(low bits) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_TagLo: mips_cop0_reg = 28;
#[doc = " Cache Tag register(high bits) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_TagHi: mips_cop0_reg = 29;
#[doc = " Error Exception Program Counter (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_ErrorPC: mips_cop0_reg = 30;
pub type mips_cop0_reg = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn ChangeGP(gp: *mut ::core::ffi::c_void) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn SetGP(gp: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetGP() -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub static mut _gp: *mut ::core::ffi::c_void;
}
pub const INTC_GS: _bindgen_ty_1 = 0;
pub const INTC_SBUS: _bindgen_ty_1 = 1;
pub const INTC_VBLANK_S: _bindgen_ty_1 = 2;
pub const INTC_VBLANK_E: _bindgen_ty_1 = 3;
pub const INTC_VIF0: _bindgen_ty_1 = 4;
pub const INTC_VIF1: _bindgen_ty_1 = 5;
pub const INTC_VU0: _bindgen_ty_1 = 6;
pub const INTC_VU1: _bindgen_ty_1 = 7;
pub const INTC_IPU: _bindgen_ty_1 = 8;
pub const INTC_TIM0: _bindgen_ty_1 = 9;
pub const INTC_TIM1: _bindgen_ty_1 = 10;
pub const INTC_TIM2: _bindgen_ty_1 = 11;
pub const INTC_SFIFO: _bindgen_ty_1 = 13;
pub const INTC_VU0WD: _bindgen_ty_1 = 14;
#[doc = " EE Interrupt Controller (INTC) interrupt numbers"]
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const DMAC_VIF0: _bindgen_ty_2 = 0;
pub const DMAC_VIF1: _bindgen_ty_2 = 1;
pub const DMAC_GIF: _bindgen_ty_2 = 2;
pub const DMAC_FROM_IPU: _bindgen_ty_2 = 3;
pub const DMAC_TO_IPU: _bindgen_ty_2 = 4;
pub const DMAC_SIF0: _bindgen_ty_2 = 5;
pub const DMAC_SIF1: _bindgen_ty_2 = 6;
pub const DMAC_SIF2: _bindgen_ty_2 = 7;
pub const DMAC_FROM_SPR: _bindgen_ty_2 = 8;
pub const DMAC_TO_SPR: _bindgen_ty_2 = 9;
pub const DMAC_CIS: _bindgen_ty_2 = 13;
pub const DMAC_MEIS: _bindgen_ty_2 = 14;
pub const DMAC_BEIS: _bindgen_ty_2 = 15;
#[doc = " EE Direct Memory Access Controller (DMAC) interrupt numbers"]
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ee_sema {
    pub count: ::core::ffi::c_int,
    pub max_count: ::core::ffi::c_int,
    pub init_count: ::core::ffi::c_int,
    pub wait_threads: ::core::ffi::c_int,
    pub attr: u32_,
    pub option: u32_,
}
pub type ee_sema_t = t_ee_sema;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ee_thread {
    pub status: ::core::ffi::c_int,
    pub func: *mut ::core::ffi::c_void,
    pub stack: *mut ::core::ffi::c_void,
    pub stack_size: ::core::ffi::c_int,
    pub gp_reg: *mut ::core::ffi::c_void,
    pub initial_priority: ::core::ffi::c_int,
    pub current_priority: ::core::ffi::c_int,
    pub attr: u32_,
    pub option: u32_,
}
pub type ee_thread_t = t_ee_thread;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ee_thread_status {
    pub status: ::core::ffi::c_int,
    pub func: *mut ::core::ffi::c_void,
    pub stack: *mut ::core::ffi::c_void,
    pub stack_size: ::core::ffi::c_int,
    pub gp_reg: *mut ::core::ffi::c_void,
    pub initial_priority: ::core::ffi::c_int,
    pub current_priority: ::core::ffi::c_int,
    pub attr: u32_,
    pub option: u32_,
    pub waitType: u32_,
    pub waitId: u32_,
    pub wakeupCount: u32_,
}
pub type ee_thread_status_t = t_ee_thread_status;
pub const CPU_CONFIG_CPU_CONFIG_ENABLE_DIE: CPU_CONFIG = 0;
pub const CPU_CONFIG_CPU_CONFIG_ENABLE_ICE: CPU_CONFIG = 1;
pub const CPU_CONFIG_CPU_CONFIG_ENABLE_DCE: CPU_CONFIG = 2;
pub const CPU_CONFIG_CPU_CONFIG_DISBLE_DIE: CPU_CONFIG = 3;
pub const CPU_CONFIG_CPU_CONFIG_DISBLE_ICE: CPU_CONFIG = 4;
pub const CPU_CONFIG_CPU_CONFIG_DISBLE_DCE: CPU_CONFIG = 5;
#[doc = " CpuConfig options"]
pub type CPU_CONFIG = ::core::ffi::c_uint;
pub const COP0_INDEX: _bindgen_ty_3 = 0;
pub const COP0_RANDOM: _bindgen_ty_3 = 1;
pub const COP0_ENTRYLO0: _bindgen_ty_3 = 2;
pub const COP0_ENTRYLO1: _bindgen_ty_3 = 3;
pub const COP0_CONTEXT: _bindgen_ty_3 = 4;
pub const COP0_PAGEMASK: _bindgen_ty_3 = 5;
pub const COP0_WIRED: _bindgen_ty_3 = 6;
pub const COP0_BADVADDR: _bindgen_ty_3 = 8;
pub const COP0_COUNT: _bindgen_ty_3 = 9;
pub const COP0_ENTRYHI: _bindgen_ty_3 = 10;
pub const COP0_COMPARE: _bindgen_ty_3 = 11;
pub const COP0_STATUS: _bindgen_ty_3 = 12;
pub const COP0_CAUSE: _bindgen_ty_3 = 13;
pub const COP0_EPC: _bindgen_ty_3 = 14;
pub const COP0_PRID: _bindgen_ty_3 = 15;
pub const COP0_CONFIG: _bindgen_ty_3 = 16;
pub const COP0_BADPADDR: _bindgen_ty_3 = 23;
pub const COP0_DEBUG: _bindgen_ty_3 = 24;
pub const COP0_PERF: _bindgen_ty_3 = 25;
pub const COP0_TAGLO: _bindgen_ty_3 = 28;
pub const COP0_TAGHI: _bindgen_ty_3 = 29;
pub const COP0_ERROREPC: _bindgen_ty_3 = 30;
#[doc = " Cop0 Register for (i)GetCop0 and (i)SetCop0"]
pub type _bindgen_ty_3 = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn _InitSys();
}
unsafe extern "C" {
    pub fn TerminateLibrary();
}
unsafe extern "C" {
    pub fn InitThread() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iWakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iRotateThreadReadyQueue(priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn iSuspendThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn InitTLBFunctions();
}
unsafe extern "C" {
    pub fn InitTLB();
}
unsafe extern "C" {
    pub fn Exit(exit_code: s32) -> !;
}
unsafe extern "C" {
    pub fn ExecPS2(
        entry: *mut ::core::ffi::c_void,
        gp: *mut ::core::ffi::c_void,
        num_args: ::core::ffi::c_int,
        args: *mut *mut ::core::ffi::c_char,
    ) -> s32;
}
unsafe extern "C" {
    pub fn LoadExecPS2(
        filename: *const ::core::ffi::c_char,
        num_args: s32,
        args: *mut *mut ::core::ffi::c_char,
    ) -> !;
}
unsafe extern "C" {
    pub fn ExecOSD(num_args: ::core::ffi::c_int, args: *mut *mut ::core::ffi::c_char) -> !;
}
unsafe extern "C" {
    pub fn InitAlarm();
}
unsafe extern "C" {
    pub fn InitExecPS2();
}
unsafe extern "C" {
    pub fn InitOsd();
}
unsafe extern "C" {
    pub fn PatchIsNeeded() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn InitDebug();
}
unsafe extern "C" {
    pub fn DIntr() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn EIntr() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn EnableIntc(intc: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DisableIntc(intc: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn EnableDmac(dmac: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DisableDmac(dmac: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iEnableIntc(intc: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iDisableIntc(intc: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iEnableDmac(dmac: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iDisableDmac(dmac: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SyncDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn iSyncDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn InvalidDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn iInvalidDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn ResetEE(init_bitfield: u32_);
}
unsafe extern "C" {
    pub fn SetGsCrt(interlace: s16, pal_ntsc: s16, field: s16);
}
unsafe extern "C" {
    pub fn KExit(exit_code: s32) -> !;
}
unsafe extern "C" {
    pub fn _LoadExecPS2(
        filename: *const ::core::ffi::c_char,
        num_args: s32,
        args: *mut *mut ::core::ffi::c_char,
    ) -> !;
}
unsafe extern "C" {
    pub fn _ExecPS2(
        entry: *mut ::core::ffi::c_void,
        gp: *mut ::core::ffi::c_void,
        num_args: ::core::ffi::c_int,
        args: *mut *mut ::core::ffi::c_char,
    ) -> s32;
}
unsafe extern "C" {
    pub fn RFU009(arg0: u32_, arg1: u32_);
}
unsafe extern "C" {
    pub fn AddSbusIntcHandler(
        cause: s32,
        handler: ::core::option::Option<unsafe extern "C" fn(call: ::core::ffi::c_int)>,
    ) -> s32;
}
unsafe extern "C" {
    pub fn RemoveSbusIntcHandler(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn Interrupt2Iop(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn SetVTLBRefillHandler(handler_num: s32, handler_func: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn SetVCommonHandler(handler_num: s32, handler_func: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn SetVInterruptHandler(handler_num: s32, handler_func: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn AddIntcHandler(
        cause: s32,
        handler_func: ::core::option::Option<unsafe extern "C" fn(cause: s32) -> s32>,
        next: s32,
    ) -> s32;
}
unsafe extern "C" {
    pub fn AddIntcHandler2(
        cause: s32,
        handler_func: ::core::option::Option<
            unsafe extern "C" fn(
                cause: s32,
                arg: *mut ::core::ffi::c_void,
                addr: *mut ::core::ffi::c_void,
            ) -> s32,
        >,
        next: s32,
        arg: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn RemoveIntcHandler(cause: s32, handler_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn AddDmacHandler(
        channel: s32,
        handler: ::core::option::Option<unsafe extern "C" fn(channel: s32) -> s32>,
        next: s32,
    ) -> s32;
}
unsafe extern "C" {
    pub fn AddDmacHandler2(
        channel: s32,
        handler: ::core::option::Option<
            unsafe extern "C" fn(
                channel: s32,
                arg: *mut ::core::ffi::c_void,
                addr: *mut ::core::ffi::c_void,
            ) -> s32,
        >,
        next: s32,
        arg: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn RemoveDmacHandler(channel: s32, handler_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _EnableIntc(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn _DisableIntc(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn _EnableDmac(channel: s32) -> s32;
}
unsafe extern "C" {
    pub fn _DisableDmac(channel: s32) -> s32;
}
unsafe extern "C" {
    pub fn SetAlarm(
        time: u16_,
        callback: ::core::option::Option<
            unsafe extern "C" fn(alarm_id: s32, time: u16_, common: *mut ::core::ffi::c_void),
        >,
        common: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn _SetAlarm(
        time: u16_,
        callback: ::core::option::Option<
            unsafe extern "C" fn(alarm_id: s32, time: u16_, common: *mut ::core::ffi::c_void),
        >,
        common: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn ReleaseAlarm(alarm_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _ReleaseAlarm(alarm_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iEnableIntc(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iDisableIntc(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iEnableDmac(channel: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iDisableDmac(channel: s32) -> s32;
}
unsafe extern "C" {
    pub fn iSetAlarm(
        time: u16_,
        callback: ::core::option::Option<
            unsafe extern "C" fn(alarm_id: s32, time: u16_, common: *mut ::core::ffi::c_void),
        >,
        common: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn _iSetAlarm(
        time: u16_,
        callback: ::core::option::Option<
            unsafe extern "C" fn(alarm_id: s32, time: u16_, common: *mut ::core::ffi::c_void),
        >,
        common: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn iReleaseAlarm(alarm_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iReleaseAlarm(alarm_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn CreateThread(thread: *mut ee_thread_t) -> s32;
}
unsafe extern "C" {
    pub fn DeleteThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn StartThread(thread_id: s32, args: *mut ::core::ffi::c_void) -> s32;
}
unsafe extern "C" {
    pub fn ExitThread();
}
unsafe extern "C" {
    pub fn ExitDeleteThread();
}
unsafe extern "C" {
    pub fn TerminateThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iTerminateThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn ChangeThreadPriority(thread_id: s32, priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn iChangeThreadPriority(thread_id: s32, priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn RotateThreadReadyQueue(priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iRotateThreadReadyQueue(priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn ReleaseWaitThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iReleaseWaitThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn GetThreadId() -> s32;
}
unsafe extern "C" {
    pub fn _iGetThreadId() -> s32;
}
unsafe extern "C" {
    pub fn ReferThreadStatus(thread_id: s32, info: *mut ee_thread_status_t) -> s32;
}
unsafe extern "C" {
    pub fn iReferThreadStatus(thread_id: s32, info: *mut ee_thread_status_t) -> s32;
}
unsafe extern "C" {
    pub fn SleepThread() -> s32;
}
unsafe extern "C" {
    pub fn WakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iWakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn CancelWakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iCancelWakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn SuspendThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iSuspendThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn ResumeThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iResumeThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn RFU059() -> u8_;
}
unsafe extern "C" {
    pub fn SetupThread(
        gp: *mut ::core::ffi::c_void,
        stack: *mut ::core::ffi::c_void,
        stack_size: s32,
        args: *mut ::core::ffi::c_void,
        root_func: *mut ::core::ffi::c_void,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn SetupHeap(heap_start: *mut ::core::ffi::c_void, heap_size: s32);
}
unsafe extern "C" {
    pub fn EndOfHeap() -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn CreateSema(sema: *mut ee_sema_t) -> s32;
}
unsafe extern "C" {
    pub fn DeleteSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn SignalSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iSignalSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn WaitSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn PollSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iPollSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn ReferSemaStatus(sema_id: s32, sema: *mut ee_sema_t) -> s32;
}
unsafe extern "C" {
    pub fn iReferSemaStatus(sema_id: s32, sema: *mut ee_sema_t) -> s32;
}
unsafe extern "C" {
    pub fn iDeleteSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn SetOsdConfigParam(addr: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetOsdConfigParam(addr: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetGsHParam(
        addr1: *mut ::core::ffi::c_void,
        addr2: *mut ::core::ffi::c_void,
        addr3: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn GetGsVParam() -> s32;
}
unsafe extern "C" {
    pub fn SetGsHParam(
        addr1: *mut ::core::ffi::c_void,
        addr2: *mut ::core::ffi::c_void,
        addr3: *mut ::core::ffi::c_void,
        addr4: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn SetGsVParam(arg1: s32);
}
unsafe extern "C" {
    pub fn PutTLBEntry(
        PageMask: ::core::ffi::c_uint,
        EntryHi: ::core::ffi::c_uint,
        EntryLo0: ::core::ffi::c_uint,
        EntryLo1: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iPutTLBEntry(
        PageMask: ::core::ffi::c_uint,
        EntryHi: ::core::ffi::c_uint,
        EntryLo0: ::core::ffi::c_uint,
        EntryLo1: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn _SetTLBEntry(
        index: ::core::ffi::c_uint,
        PageMask: ::core::ffi::c_uint,
        EntryHi: ::core::ffi::c_uint,
        EntryLo0: ::core::ffi::c_uint,
        EntryLo1: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iSetTLBEntry(
        index: ::core::ffi::c_uint,
        PageMask: ::core::ffi::c_uint,
        EntryHi: ::core::ffi::c_uint,
        EntryLo0: ::core::ffi::c_uint,
        EntryLo1: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn GetTLBEntry(
        index: ::core::ffi::c_uint,
        PageMask: *mut ::core::ffi::c_uint,
        EntryHi: *mut ::core::ffi::c_uint,
        EntryLo0: *mut ::core::ffi::c_uint,
        EntryLo1: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iGetTLBEntry(
        index: ::core::ffi::c_uint,
        PageMask: *mut ::core::ffi::c_uint,
        EntryHi: *mut ::core::ffi::c_uint,
        EntryLo0: *mut ::core::ffi::c_uint,
        EntryLo1: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn ProbeTLBEntry(
        EntryHi: ::core::ffi::c_uint,
        PageMask: *mut ::core::ffi::c_uint,
        EntryLo0: *mut ::core::ffi::c_uint,
        EntryLo1: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iProbeTLBEntry(
        EntryHi: ::core::ffi::c_uint,
        PageMask: *mut ::core::ffi::c_uint,
        EntryLo0: *mut ::core::ffi::c_uint,
        EntryLo1: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn ExpandScratchPad(page: ::core::ffi::c_uint) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn EnableIntcHandler(cause: u32_);
}
unsafe extern "C" {
    pub fn iEnableIntcHandler(cause: u32_);
}
unsafe extern "C" {
    pub fn DisableIntcHandler(cause: u32_);
}
unsafe extern "C" {
    pub fn iDisableIntcHandler(cause: u32_);
}
unsafe extern "C" {
    pub fn EnableDmacHandler(channel: u32_);
}
unsafe extern "C" {
    pub fn iEnableDmacHandler(channel: u32_);
}
unsafe extern "C" {
    pub fn DisableDmacHandler(channel: u32_);
}
unsafe extern "C" {
    pub fn iDisableDmacHandler(channel: u32_);
}
unsafe extern "C" {
    pub fn KSeg0(arg1: s32);
}
unsafe extern "C" {
    pub fn EnableCache(cache: s32) -> s32;
}
unsafe extern "C" {
    pub fn DisableCache(cache: s32) -> s32;
}
unsafe extern "C" {
    pub fn GetCop0(reg_id: s32) -> u32_;
}
unsafe extern "C" {
    pub fn FlushCache(operation: s32);
}
unsafe extern "C" {
    pub fn CpuConfig(config: u32_) -> u32_;
}
unsafe extern "C" {
    pub fn iGetCop0(reg_id: s32) -> u32_;
}
unsafe extern "C" {
    pub fn iFlushCache(operation: s32);
}
unsafe extern "C" {
    pub fn iCpuConfig(config: u32_) -> u32_;
}
unsafe extern "C" {
    pub fn SetCPUTimerHandler(handler: ::core::option::Option<unsafe extern "C" fn()>);
}
unsafe extern "C" {
    pub fn SetCPUTimer(compval: s32);
}
unsafe extern "C" {
    pub fn SetOsdConfigParam2(config: *mut ::core::ffi::c_void, size: s32, offset: s32);
}
unsafe extern "C" {
    pub fn GetOsdConfigParam2(config: *mut ::core::ffi::c_void, size: s32, offset: s32);
}
unsafe extern "C" {
    pub fn GsGetIMR() -> u64_;
}
unsafe extern "C" {
    pub fn iGsGetIMR() -> u64_;
}
unsafe extern "C" {
    pub fn GsPutIMR(imr: u64_) -> u64_;
}
unsafe extern "C" {
    pub fn iGsPutIMR(imr: u64_) -> u64_;
}
unsafe extern "C" {
    pub fn SetPgifHandler(handler: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn SetVSyncFlag(arg1: *mut u32_, arg2: *mut u64_);
}
unsafe extern "C" {
    pub fn SetSyscall(syscall_num: s32, handler: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn _print(fmt: *const ::core::ffi::c_char, ...);
}
unsafe extern "C" {
    pub fn sceSifStopDma();
}
unsafe extern "C" {
    pub fn sceiSifDmaStat(trid: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn isceSifSetDma(
        dmat: *mut SifDmaTransfer_t,
        count: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn sceSifSetDChain();
}
unsafe extern "C" {
    pub fn isceSifSetDChain();
}
unsafe extern "C" {
    pub fn sceSifSetReg(
        register_num: u32_,
        register_value: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn sceSifGetReg(register_num: u32_) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn _ExecOSD(num_args: ::core::ffi::c_int, args: *mut *mut ::core::ffi::c_char) -> !;
}
unsafe extern "C" {
    pub fn Deci2Call(arg1: s32, arg2: *mut u32_) -> s32;
}
unsafe extern "C" {
    pub fn PSMode();
}
unsafe extern "C" {
    pub fn MachineType() -> s32;
}
unsafe extern "C" {
    pub fn GetMemorySize() -> s32;
}
unsafe extern "C" {
    pub fn _GetGsDxDyOffset(
        mode: ::core::ffi::c_int,
        dx: *mut ::core::ffi::c_int,
        dy: *mut ::core::ffi::c_int,
        dw: *mut ::core::ffi::c_int,
        dh: *mut ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn _InitTLB() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SetMemoryMode(mode: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn GetMemoryMode() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn _SyncDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn _InvalidDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetSyscallHandler(syscall_no: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn GetExceptionHandler(except_no: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn GetInterruptHandler(intr_no: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn kCopy(
        dest: *mut ::core::ffi::c_void,
        src: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn kCopyBytes(
        dest: *mut ::core::ffi::c_void,
        src: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn Copy(
        dest: *mut ::core::ffi::c_void,
        src: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn setup(syscall_num: ::core::ffi::c_int, handler: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetEntryAddress(syscall: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn SifInitIopHeap() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SifExitIopHeap();
}
unsafe extern "C" {
    pub fn SifAllocIopHeap(size: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn SifFreeIopHeap(addr: *mut ::core::ffi::c_void) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SifLoadIopHeap(
        path: *const ::core::ffi::c_char,
        addr: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Resets IOP\n This is a high level wrapper for SifIopReset\n @param arg a const character pointer for path to module that will be loaded afterwards or an empty string. NULL must not be specified.\n @return 1 for success or 0 for failure."]
    pub fn SifIopReboot(arg: *const ::core::ffi::c_char) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Resets IOP\n @param arg a const character pointer for path to module that will be loaded afterwards or a blank. NULL is not officially supported, but is supported for backward-compatibility with old homebrew projects.\n @param mode Bitmask for optional settings. 0x80000000 for verbose messages and 0x100 for magicgate.\n @return 1 for success or 0 for failure."]
    pub fn SifIopReset(
        arg: *const ::core::ffi::c_char,
        mode: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @return 1 for SIF initialized or 0 for not initialized."]
    pub fn SifIopIsAlive() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @return 1 for bootup complete or 0 for incomplete."]
    pub fn SifIopSync() -> ::core::ffi::c_int;
}
#[doc = " SIF command."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_SifCmdHeader {
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
    #[doc = " Destination address for payload. Can be NULL if there is no payload."]
    pub dest: *mut ::core::ffi::c_void,
    #[doc = " Function number of function to call."]
    pub cid: ::core::ffi::c_int,
    #[doc = " Can be freely used."]
    pub opt: u32_,
}
impl t_SifCmdHeader {
    #[inline]
    pub fn psize(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 8u8) as u32) }
    }
    #[inline]
    pub fn set_psize(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 8u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn psize_raw(this: *const Self) -> u32_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                8u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_psize_raw(this: *mut Self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                8u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn dsize(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(8usize, 24u8) as u32) }
    }
    #[inline]
    pub fn set_dsize(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(8usize, 24u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn dsize_raw(this: *const Self) -> u32_ {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                8usize,
                24u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_dsize_raw(this: *mut Self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                8usize,
                24u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(psize: u32_, dsize: u32_) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 8u8, {
            let psize: u32 = unsafe { ::core::mem::transmute(psize) };
            psize as u64
        });
        __bindgen_bitfield_unit.set(8usize, 24u8, {
            let dsize: u32 = unsafe { ::core::mem::transmute(dsize) };
            dsize as u64
        });
        __bindgen_bitfield_unit
    }
}
#[doc = " SIF command."]
pub type SifCmdHeader_t = t_SifCmdHeader;
#[doc = " Structure for remotely (over the SIF) changing the value of a software register (SREG).\n There are 32 software registers (0 - 31). Registers 0-7 are used by the system."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_SifCmdSRegData {
    pub header: SifCmdHeader_t,
    pub index: ::core::ffi::c_int,
    pub value: ::core::ffi::c_uint,
}
#[doc = " Structure for remotely (over the SIF) changing the value of a software register (SREG).\n There are 32 software registers (0 - 31). Registers 0-7 are used by the system."]
pub type SifCmdSRegData_t = t_SifCmdSRegData;
pub type SifCmdHandler_t = ::core::option::Option<
    unsafe extern "C" fn(data: *mut ::core::ffi::c_void, harg: *mut ::core::ffi::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_SifCmdHandlerData {
    pub handler: SifCmdHandler_t,
    pub harg: *mut ::core::ffi::c_void,
}
pub type SifCmdHandlerData_t = t_SifCmdHandlerData;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_SifCmdSysHandlerData {
    pub handler: SifCmdHandler_t,
    pub harg: *mut ::core::ffi::c_void,
    pub unknown08: *mut ::core::ffi::c_void,
}
pub type SifCmdSysHandlerData_t = t_SifCmdSysHandlerData;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _iop_reset_pkt {
    pub header: t_SifCmdHeader,
    pub arglen: ::core::ffi::c_int,
    pub mode: ::core::ffi::c_int,
    pub arg: [::core::ffi::c_char; 80usize],
}
pub type SifCmdResetData_t = _iop_reset_pkt;
unsafe extern "C" {
    pub fn sceSifInitCmd();
}
unsafe extern "C" {
    pub fn sceSifExitCmd();
}
unsafe extern "C" {
    pub fn sceSifGetSreg(sreg: ::core::ffi::c_int) -> ::core::ffi::c_uint;
}
unsafe extern "C" {
    pub fn sceSifSetSreg(sreg: ::core::ffi::c_int, value: ::core::ffi::c_uint);
}
unsafe extern "C" {
    pub fn sceSifSetCmdBuffer(db: *mut SifCmdHandlerData_t, size: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn sceSifSetSysCmdBuffer(db: *mut SifCmdSysHandlerData_t, size: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn sceSifAddCmdHandler(
        cid: ::core::ffi::c_int,
        handler: SifCmdHandler_t,
        harg: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn sceSifRemoveCmdHandler(cid: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn sceSifSendCmd(
        cid: ::core::ffi::c_int,
        packet: *mut ::core::ffi::c_void,
        packet_size: ::core::ffi::c_int,
        src_extra: *mut ::core::ffi::c_void,
        dest_extra: *mut ::core::ffi::c_void,
        size_extra: ::core::ffi::c_int,
    ) -> ::core::ffi::c_uint;
}
unsafe extern "C" {
    pub fn isceSifSendCmd(
        cid: ::core::ffi::c_int,
        packet: *mut ::core::ffi::c_void,
        packet_size: ::core::ffi::c_int,
        src_extra: *mut ::core::ffi::c_void,
        dest_extra: *mut ::core::ffi::c_void,
        size_extra: ::core::ffi::c_int,
    ) -> ::core::ffi::c_uint;
}
unsafe extern "C" {
    pub fn sceSifWriteBackDCache(ptr: *mut ::core::ffi::c_void, size: ::core::ffi::c_int);
}
pub const _lf_val_types_LF_VAL_BYTE: _lf_val_types = 0;
pub const _lf_val_types_LF_VAL_SHORT: _lf_val_types = 1;
pub const _lf_val_types_LF_VAL_LONG: _lf_val_types = 2;
pub type _lf_val_types = ::core::ffi::c_uint;
pub const _lf_functions_LF_F_MOD_LOAD: _lf_functions = 0;
pub const _lf_functions_LF_F_ELF_LOAD: _lf_functions = 1;
pub const _lf_functions_LF_F_SET_ADDR: _lf_functions = 2;
pub const _lf_functions_LF_F_GET_ADDR: _lf_functions = 3;
pub const _lf_functions_LF_F_MG_MOD_LOAD: _lf_functions = 4;
pub const _lf_functions_LF_F_MG_ELF_LOAD: _lf_functions = 5;
pub const _lf_functions_LF_F_MOD_BUF_LOAD: _lf_functions = 6;
pub const _lf_functions_LF_F_MOD_STOP: _lf_functions = 7;
pub const _lf_functions_LF_F_MOD_UNLOAD: _lf_functions = 8;
pub const _lf_functions_LF_F_SEARCH_MOD_BY_NAME: _lf_functions = 9;
pub const _lf_functions_LF_F_SEARCH_MOD_BY_ADDRESS: _lf_functions = 10;
pub const _lf_functions_LF_F_GET_VERSION: _lf_functions = 255;
pub type _lf_functions = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ExecData {
    pub epc: u32_,
    pub gp: u32_,
    pub sp: u32_,
    pub dummy: u32_,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct _lf_iop_val_arg {
    pub p: _lf_iop_val_arg__bindgen_ty_1,
    pub type_: ::core::ffi::c_int,
    pub val: _lf_iop_val_arg__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _lf_iop_val_arg__bindgen_ty_1 {
    pub iop_addr: u32_,
    pub result: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _lf_iop_val_arg__bindgen_ty_2 {
    pub b: u8_,
    pub s: u16_,
    pub l: u32_,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct _lf_module_load_arg {
    pub p: _lf_module_load_arg__bindgen_ty_1,
    pub modres: ::core::ffi::c_int,
    pub path: [::core::ffi::c_char; 252usize],
    pub args: [::core::ffi::c_char; 252usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _lf_module_load_arg__bindgen_ty_1 {
    pub arg_len: ::core::ffi::c_int,
    pub result: ::core::ffi::c_int,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct _lf_module_stop_arg {
    pub p: _lf_module_stop_arg__bindgen_ty_1,
    pub q: _lf_module_stop_arg__bindgen_ty_2,
    pub dummy: [::core::ffi::c_char; 252usize],
    pub args: [::core::ffi::c_char; 252usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _lf_module_stop_arg__bindgen_ty_1 {
    pub id: ::core::ffi::c_int,
    pub result: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _lf_module_stop_arg__bindgen_ty_2 {
    pub arg_len: ::core::ffi::c_int,
    pub modres: ::core::ffi::c_int,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union _lf_module_unload_arg {
    pub id: ::core::ffi::c_int,
    pub result: ::core::ffi::c_int,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct _lf_search_module_by_name_arg {
    pub id: ::core::ffi::c_int,
    pub dummy1: ::core::ffi::c_int,
    pub name: [::core::ffi::c_char; 252usize],
    pub dummy2: [::core::ffi::c_char; 252usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct _lf_search_module_by_address_arg {
    pub p: _lf_search_module_by_address_arg__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _lf_search_module_by_address_arg__bindgen_ty_1 {
    pub ptr: *const ::core::ffi::c_void,
    pub id: ::core::ffi::c_int,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct _lf_elf_load_arg {
    pub epc: u32_,
    pub gp: u32_,
    pub path: [::core::ffi::c_char; 252usize],
    pub secname: [::core::ffi::c_char; 252usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct _lf_module_buffer_load_arg {
    pub p: _lf_module_buffer_load_arg__bindgen_ty_1,
    pub q: _lf_module_buffer_load_arg__bindgen_ty_2,
    pub unused: [::core::ffi::c_char; 252usize],
    pub args: [::core::ffi::c_char; 252usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _lf_module_buffer_load_arg__bindgen_ty_1 {
    pub ptr: *mut ::core::ffi::c_void,
    pub result: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _lf_module_buffer_load_arg__bindgen_ty_2 {
    pub arg_len: ::core::ffi::c_int,
    pub modres: ::core::ffi::c_int,
}
unsafe extern "C" {
    #[doc = " Initialize the LOADFILE library.\n @ingroup loadfile\n\n @returns 0 on success, E_SIF_RPC_BIND if unable to connect to the server.\n\n Initializes the LOADFILE API and binds to the remote LOADFILE RPC server."]
    pub fn SifLoadFileInit() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Reset the LOADFILE library.\n @ingroup loadfile\n\n Deinitializes the LOADFILE library in preparation of an IOP reset."]
    pub fn SifLoadFileExit();
}
unsafe extern "C" {
    #[doc = " Load and execute an IRX module.\n @ingroup loadfile\n\n @param path    Path to an IRX module\n @param arg_len Length, in bytes, of the argument list\n @param args    List of arguments to pass to the IRX on startup\n\n @returns The ID of the loaded module on success, or an error if the module\n couldn't be loaded.\n\n Loads an IRX module from the specified path, and executes it.  The args\n parameter specifies a list of arguments that are passed to the loaded module\n as the argv[] array.  Each argument string in args must be seperated by NUL ('\\\\0').\n Pass the length of the entire args list, including the NUL seperators in the args_len\n parameter.\n\n @note By default, modules cannot be loaded directly from the memory card.  If you need to\n load modules from the memory card, you should use ::SifExecModuleFile or link with the\n sbv-lite library (http://www.0xd6.org).\n\n @see SifExecModuleFile"]
    pub fn SifLoadModule(
        path: *const ::core::ffi::c_char,
        arg_len: ::core::ffi::c_int,
        args: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Load and execute and IRX module, and retrieve the module's load status.\n @ingroup loadfile\n\n @param path    Path to an IRX module\n @param arg_len Length, in bytes, of the argument list\n @param args    List of arguments to pass to the IRX on startup\n @param mod_res Pointer to a variable that will store the return value from the IRX's _start() function\n\n @returns The ID of the loaded module on success, or an error if the module\n couldn't be loaded.\n\n Loads an IRX module from the specified path, and executes it.  See ::SifLoadModule for\n details on the arg_len and args parameters.  If mod_res is non-NULL, the result code from\n the module's _start() function is stored here.\n\n @see SifLoadModule"]
    pub fn SifLoadStartModule(
        path: *const ::core::ffi::c_char,
        arg_len: ::core::ffi::c_int,
        args: *const ::core::ffi::c_char,
        mod_res: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Load and execute an IRX module encrypted with MagicGate.\n @ingroup loadfile\n\n @param path    Path to an IRX module\n @param arg_len Length, in bytes, of the argument list\n @param args    List of arguments to pass to the IRX on startup\n\n @returns The ID of the loaded module on success, or an error if the module\n couldn't be loaded.\n\n There is no real use for this function; it is only included in ps2lib for completeness.\n\n @see SifLoadModule"]
    pub fn SifLoadModuleEncrypted(
        path: *const ::core::ffi::c_char,
        arg_len: ::core::ffi::c_int,
        args: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Load and execute an IRX module from a buffer in IOP RAM.\n @ingroup loadfile\n\n @param ptr     Pointer to a buffer in IOP RAM where the IRX module will be loaded from\n @param arg_len Length, in bytes, of the argument list\n @param args    List of arguments to pass to the IRX on startup\n\n @returns The ID of the loaded module on success, or an error if the module couldn't\n be loaded.\n\n Loads an IRX module from a buffer located in IOP RAM.  See ::SifLoadModule for details on\n the arg_len and args parameters.\n\n @note If you need to load an IRX module onto the IOP directly from a buffer in EE RAM, then\n use ::SifExecModuleBuffer.\n\n @see SifLoadModule, SifExecModuleBuffer"]
    pub fn SifLoadModuleBuffer(
        ptr: *mut ::core::ffi::c_void,
        arg_len: ::core::ffi::c_int,
        args: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Load and execute an IRX module from a buffer in IOP RAM, and retrieve the module's load status.\n @ingroup loadfile\n\n @param ptr     Pointer to a buffer in IOP RAM where the IRX module will be loaded from\n @param arg_len Length, in bytes, of the argument list\n @param args    List of arguments to pass to the IRX on startup\n @param mod_res Pointer to a variable that will store the return value from the IRX's _start() function\n\n @returns The ID of the loaded module on success, or an error if the module\n couldn't be loaded.\n\n Loads an IRX module from a buffer located in IOP RAM.  See ::SifLoadModule for details on\n the arg_len and args parameters.  If mod_res is non-NULL, the result code from the module's\n _start() function is stored here.\n\n @note If you need to load an IRX module onto the IOP directly from a buffer in EE RAM, then\n use ::SifExecModuleBuffer.\n\n @see SifLoadModule, SifExecModuleBuffer"]
    pub fn SifLoadStartModuleBuffer(
        ptr: *mut ::core::ffi::c_void,
        arg_len: ::core::ffi::c_int,
        args: *const ::core::ffi::c_char,
        mod_res: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SifStopModule(
        id: ::core::ffi::c_int,
        arg_len: ::core::ffi::c_int,
        args: *const ::core::ffi::c_char,
        mod_res: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SifUnloadModule(id: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SifSearchModuleByName(name: *const ::core::ffi::c_char) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SifSearchModuleByAddress(ptr: *const ::core::ffi::c_void) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Load the specified section of an ELF executable into EE RAM.\n @ingroup loadfile\n\n @param path    Path to an ELF executable\n @param secname The name of a single section to load from the ELF, or \"all\" to load all sections\n @param data    Pointer to a variable that will store information about the loaded executable\n\n @returns 0 on success, or an error code if an error occurred.\n\n Loads the section secname from the ELF file specified by path into EE RAM.\n\n data points to a t_ExecData structure where information about the loaded\n section will be returned.\n\n @warning Don't ever use this function, it does not work as intended."]
    pub fn SifLoadElfPart(
        path: *const ::core::ffi::c_char,
        secname: *const ::core::ffi::c_char,
        data: *mut t_ExecData,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Load an ELF executable into EE RAM.\n @ingroup loadfile\n\n @param path Path to an ELF executable\n @param data Pointer to a variable that will store information about the loaded executable\n\n @returns 0 on success, or an error code if an error occurred.\n\n Loads the ELF executable specified by path into EE RAM.  data points to a\n t_ExecData structure where information about the loaded executable will be returned.\n\n @warning It's possible to overwrite your program if the ELF that you're trying to\n load overlaps your program's memory space.  Always ensure that the target ELF will\n load before or after your program's code and data addresses."]
    pub fn SifLoadElf(
        path: *const ::core::ffi::c_char,
        data: *mut t_ExecData,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Load a MagicGate-encrypted ELF executable into EE RAM.\n @ingroup loadfile\n\n @param path Path to an ELF executable\n @param data Pointer to a variable that will store information about the loaded executable\n\n @returns 0 on success, or an error code if an error occurred.\n\n There is no real use for this function; it is only included in ps2lib for completeness.\n\n @see SifLoadElf"]
    pub fn SifLoadElfEncrypted(
        path: *const ::core::ffi::c_char,
        data: *mut t_ExecData,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Write a value to an address within the IOP's memory space.\n @ingroup loadfile\n\n @param iop_addr Address to modify in the IOP's address space\n @param val      Data to write at iop_addr\n @param type     A type describing the size of the val argument\n\n @returns Previous value at iop_addr  on success (?), or an error code if an\n error occurred.\n\n Writes the data passed in val to the IOP address specified by iop_addr.  Use\n the following types specify the size of data write:\n - ::LF_VAL_BYTE to write an 8-bit value\n - ::LF_VAL_SHORT to write a 16-bit value\n - ::LF_VAL_LONG to write a 32-bit value\n\n @note Because iop_addr can be any address within the IOP's address space, it's\n possible to modify IOP hardware registers.  However, in most cases the EE can\n modify the IOP's hardware registers directly so there is little use for this function.\n\n @see SifIopGetVal"]
    pub fn SifIopSetVal(
        iop_addr: u32_,
        val: ::core::ffi::c_int,
        type_: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Read a value from an address within the IOP's memory space.\n @ingroup loadfile\n\n @param iop_addr Address within the IOP's address space to read from\n @param val      Pointer to a variable that stores the value read\n @param type     A type describing the size of the data to read\n\n @returns 0 on success, or an error code if an error occurred.\n\n Reads data of the size specified by type from the IOP address specified by\n iop_addr.  Use the following types to specify the size of the data to read:\n - ::LF_VAL_BYTE to write an 8-bit value\n - ::LF_VAL_SHORT to write a 16-bit value\n - ::LF_VAL_LONG to write a 32-bit value\n\n @note Because iop_addr can be any address within the IOP's address space, it's\n possible to read from IOP hardware registers.  However, in most cases the EE can\n read the IOP's hardware registers directly so there is little use for this function.\n @see SifIopSetVal"]
    pub fn SifIopGetVal(
        iop_addr: u32_,
        val: *mut ::core::ffi::c_void,
        type_: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Transfer an IRX module from EE RAM to IOP RAM and execute it.\n @ingroup loadfile\n\n @param ptr     Pointer to a buffer in EE RAM where the IRX module will be loaded from\n @param size    Size of the buffer in EE RAM that contains the IRX module\n @param arg_len Length, in bytes, of the argument list\n @param args    List of arguments to pass to the IRX on startup\n @param mod_res Pointer to a variable that will store the return value from the IRX's _start() function\n\n @returns The ID of the loaded module on success, or an error if the module couldn't\n be loaded.\n\n Transfers an IRX module stored in a buffer in EE RAM to the IOP, and calls ::SifLoadModuleBuffer to\n load and execute the module.  See ::SifLoadModule for details on the arg_len and args parameters.\n If mod_res is non-NULL, the result code from the module's _start() function is stored here.\n\n @see SifLoadModule, SifLoadModuleBuffer"]
    pub fn SifExecModuleBuffer(
        ptr: *mut ::core::ffi::c_void,
        size: u32_,
        arg_len: u32_,
        args: *const ::core::ffi::c_char,
        mod_res: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Read an IRX module from a file into IOP RAM and execute it.\n @ingroup loadfile\n\n @param path    Path to an IRX module\n @param arg_len Length, in bytes, of the argument list\n @param args    List of arguments to pass to the IRX on startup\n @param mod_res Pointer to a variable that will store the return value from the IRX's _start() function\n\n @returns The ID of the loaded module on success, or an error if the module\n couldn't be loaded.\n\n Loads an IRX module from the specified path into a buffer on the IOP, then calls ::SifLoadModuleBuffer\n to load and execute the module.  See ::SifLoadModule for details on the arg_len and args parameters.\n This function is useful if you need to load an IRX module from a prohibited device, such as the memory card.\n\n @see SifLoadModule, SifLoadModuleBuffer"]
    pub fn SifExecModuleFile(
        path: *const ::core::ffi::c_char,
        arg_len: u32_,
        args: *const ::core::ffi::c_char,
        mod_res: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Low-level function for loading and executing an IRX module.\n @ingroup loadfile\n\n @param path     Path to an IRX module\n @param arg_len  Length, in bytes, of the argument list\n @param args     List of arguments to pass to the IRX on startup\n @param *modres  Pointer to a variable that will store the return value from the IRX's _start() function\n @param fno      Function number of function to execute.\n @param dontwait Whether to wait for the module's _start function to finish executing.\n\n @returns The ID of the loaded module on success, or an error if the module\n couldn't be loaded.\n\n Unless required, use the higher-level functions instead.\n\n @see SifLoadModule, SifLoadModuleBuffer, SifLoadModuleEncrypted"]
    pub fn _SifLoadModule(
        path: *const ::core::ffi::c_char,
        arg_len: ::core::ffi::c_int,
        args: *const ::core::ffi::c_char,
        modres: *mut ::core::ffi::c_int,
        fno: ::core::ffi::c_int,
        dontwait: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
pub type __builtin_va_list = *mut ::core::ffi::c_void;
