[package]
name = "bevy-ps2"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/ps2sdk-sys",
    "vendor/prussia/prussia_rt"
]

[dependencies]
# cstr_core = "0.2.6"

# # Shared dependencies...
# bevy_ecs = { version = "0.19.1", default-features = false }
#bevy_app = { version = "0.19.1", default-features = false }
# bevy_math = { version = "0.19.1", default-features = false }
# bevy_transform = { version = "0.19.1", default-features = false }
#bevy_transform = { version = "0.19.1", default-features = false }

# PC host...
[target.'cfg(not(target_vendor = "sony"))'.dependencies]
bevy = { version = "0.19.1" } # Full default features for desktop iteration
# bevy_transform = { version = "0.19.1" }
bevy_ecs = { version = "0.19.1" }
#bevy_mesh = { version = "0.19.1" }
bevy_color = { version = "0.19.1" }
bevy_animation = { version = "0.19.1" }

# PS2 host...
[target.'cfg(target_vendor = "sony")'.dependencies]
ps2sdk-sys = { path = "crates/ps2sdk-sys" }
prussia_rt = { path = "vendor/prussia/prussia_rt" }

bevy_app = { version = "0.19.1", default-features = false }
bevy_ecs = { version = "0.19.1", default-features = false }
bevy_time = { version = "0.19.1", default-features = false }
bevy_transform = { version = "0.19.1", default-features = false }
# bevy_hierarchy = { version = "0.19.1", default-features = false }
bevy_animation = { version = "0.19.1", default-features = false }
bevy_color = { version = "0.19.1", default-features = false }

# Force critical ecosystem crates into no_std mode
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }
indexmap = { version = "2", default-features = false }
foldhash = { version = "0.1", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"