[alias]
build-ps2 = "build --target mips64el-sony-ps2.json -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"
build-ps2-release = "build --target mips64el-sony-ps2.json --release -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"
build-ps2-x32 = "build --target mipsel-sony-ps2.json -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"

[unstable]
json-target-spec = true
script = true

[target.'cfg(target_vendor = "sony")']
linker = "mips64r5900el-ps2-elf-gcc"
runner = "cargo ./scripts/pcsx2-test-runner.rs"

rustflags = [
  # "-C", "target-feature=+mips3,+soft-float",
  # "-C", "relocation-model=static",
  # "-C", "link-arg=-Wl,--gc-sections",

  # Strip debug symbols
  # "-C", "link-arg=-Wl,-s",

  # Linker group & dependencies
  # "-C", "link-arg=-Wl,--start-group",
  # "-C", "link-arg=-lc",
  # "-C", "link-arg=-lcglue",
  # "-C", "link-arg=-lkernel",
  # "-C", "link-arg=-latomic",
  # "-C", "link-arg=-lpthreadglue",
  # "-C", "link-arg=-lpthread",
  # "-C", "link-arg=-ldebug",
  # "-C", "link-arg=-Wl,--end-group",
]

# [env]
# LD_LIBRARY_PATH = { value = "", relative = false, force = false }
