/* automatically generated by rust-bindgen 0.72.1 */

pub const SIF_DMA_INT_I: u32 = 2;
pub const SIF_DMA_INT_O: u32 = 4;
pub const SIF_DMA_ERT: u32 = 64;
pub const SIF_REG_ID_SYSTEM: u32 = 2147483648;
pub const SIF_STAT_SIFINIT: u32 = 65536;
pub const SIF_STAT_CMDINIT: u32 = 131072;
pub const SIF_STAT_BOOTEND: u32 = 262144;
pub const TH_SELF: u32 = 0;
pub const MAX_THREADS: u32 = 256;
pub const MAX_SEMAPHORES: u32 = 256;
pub const MAX_PRIORITY: u32 = 128;
pub const MAX_HANDLERS: u32 = 128;
pub const MAX_ALARMS: u32 = 64;
pub const WRITEBACK_DCACHE: u32 = 0;
pub const INVALIDATE_DCACHE: u32 = 1;
pub const INVALIDATE_ICACHE: u32 = 2;
pub const INVALIDATE_CACHE: u32 = 3;
pub const INIT_DMAC: u32 = 1;
pub const INIT_VU1: u32 = 2;
pub const INIT_VIF1: u32 = 4;
pub const INIT_GIF: u32 = 8;
pub const INIT_VU0: u32 = 16;
pub const INIT_VIF0: u32 = 32;
pub const INIT_IPU: u32 = 64;
pub const THS_RUN: u32 = 1;
pub const THS_READY: u32 = 2;
pub const THS_WAIT: u32 = 4;
pub const THS_SUSPEND: u32 = 8;
pub const THS_WAITSUSPEND: u32 = 12;
pub const THS_DORMANT: u32 = 16;
pub const TSW_NONE: u32 = 0;
pub const TSW_SLEEP: u32 = 1;
pub const TSW_SEMA: u32 = 2;
pub const CPU_DATA_CACHE: u32 = 1;
pub const CPU_INSTRUCTION_CACHE: u32 = 2;
pub type u8_ = ::core::ffi::c_uchar;
pub type u16_ = ::core::ffi::c_ushort;
pub type vu8 = u8_;
pub type vu16 = u16_;
pub type u32_ = ::core::ffi::c_uint;
pub type u64_ = ::core::ffi::c_ulonglong;
pub type u128_ = u128;
pub type vu32 = u32_;
pub type vu64 = u64_;
pub type vu128 = u128;
pub type s8 = ::core::ffi::c_schar;
pub type s16 = ::core::ffi::c_short;
pub type vs8 = s8;
pub type vs16 = s16;
pub type s32 = ::core::ffi::c_int;
pub type s64 = ::core::ffi::c_longlong;
pub type s128 = i128;
pub type vs32 = s32;
pub type vs64 = s64;
pub type vs128 = i128;
pub type uiptr = u32_;
pub type siptr = s32;
pub type vuiptr = u32_;
pub type vsiptr = s32;
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union qword_t {
    pub qw: u128_,
    pub b: [u8_; 16usize],
    pub hw: [u16_; 8usize],
    pub sw: [u32_; 4usize],
    pub dw: [u64_; 2usize],
}
pub type wchar_t = ::core::ffi::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::core::ffi::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
pub type __gnuc_va_list = __builtin_va_list;
pub type va_list = __builtin_va_list;
#[doc = " Main -> sub-CPU command buffer (MSCOM)"]
pub const _sif_regs_SIF_REG_MAINADDR: _sif_regs = 1;
#[doc = " Sub -> main-CPU command buffer (SMCOM)"]
pub const _sif_regs_SIF_REG_SUBADDR: _sif_regs = 2;
#[doc = " Main -> sub-CPU flag (MSFLAG)"]
pub const _sif_regs_SIF_REG_MSFLAG: _sif_regs = 3;
#[doc = " Sub -> main-CPU flag (SMFLAG)"]
pub const _sif_regs_SIF_REG_SMFLAG: _sif_regs = 4;
#[doc = " Sub -> main-CPU flag (SMFLAG)"]
pub const _sif_regs_SIF_SYSREG_SUBADDR: _sif_regs = 2147483648;
#[doc = " Sub -> main-CPU flag (SMFLAG)"]
pub const _sif_regs_SIF_SYSREG_MAINADDR: _sif_regs = 2147483649;
#[doc = " Sub -> main-CPU flag (SMFLAG)"]
pub const _sif_regs_SIF_SYSREG_RPCINIT: _sif_regs = 2147483650;
pub type _sif_regs = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_SifDmaTransfer {
    pub src: *mut ::core::ffi::c_void,
    pub dest: *mut ::core::ffi::c_void,
    pub size: ::core::ffi::c_int,
    pub attr: ::core::ffi::c_int,
}
pub type SifDmaTransfer_t = t_SifDmaTransfer;
unsafe extern "C" {
    pub fn sceSifDmaStat(trid: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn sceSifSetDma(
        dmat: *mut SifDmaTransfer_t,
        count: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
#[doc = " Programmable register to select TLB entry for reading or writing (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_Index: mips_cop0_reg = 0;
#[doc = " Pseudo-random counter for TLB replacement (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_Random: mips_cop0_reg = 1;
#[doc = " Low half of TLB entry for even PFN (Physical page number) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_EntryLo0: mips_cop0_reg = 2;
#[doc = " Low half of TLB entry for odd PFN (Physical page number) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_EntryLo1: mips_cop0_reg = 3;
#[doc = " Pointer to kernel virtual PTE table (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Context: mips_cop0_reg = 4;
#[doc = " Mask that sets the TLB page size (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_PageMask: mips_cop0_reg = 5;
#[doc = " Number of wired TLB entries (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_Wired: mips_cop0_reg = 6;
#[doc = " Bad virtual address (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_BadVAddr: mips_cop0_reg = 8;
#[doc = " Timer compare (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Count: mips_cop0_reg = 9;
#[doc = " High half of TLB entry(Virtual page number and ASID) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_EntryHi: mips_cop0_reg = 10;
#[doc = " Timer compare (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Compare: mips_cop0_reg = 11;
#[doc = " Processor Status Register (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Status: mips_cop0_reg = 12;
#[doc = " Cause of the last exception taken (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Cause: mips_cop0_reg = 13;
#[doc = " Exception Program Counter (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_EPC: mips_cop0_reg = 14;
#[doc = " Processor Revision Identifier (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_PRId: mips_cop0_reg = 15;
#[doc = " Configuration Register (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_Config: mips_cop0_reg = 16;
#[doc = " Bad Physical Address (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_BadPAddr: mips_cop0_reg = 23;
#[doc = " This is used for Debug function (purpose: Debug)"]
pub const mips_cop0_reg_COP0_REG_Debug: mips_cop0_reg = 24;
#[doc = " Performance Counter and Control Register (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_Perf: mips_cop0_reg = 25;
#[doc = " Cache Tag register(low bits) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_TagLo: mips_cop0_reg = 28;
#[doc = " Cache Tag register(high bits) (purpose: MMU)"]
pub const mips_cop0_reg_COP0_REG_TagHi: mips_cop0_reg = 29;
#[doc = " Error Exception Program Counter (purpose: Exception)"]
pub const mips_cop0_reg_COP0_REG_ErrorPC: mips_cop0_reg = 30;
pub type mips_cop0_reg = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn ChangeGP(gp: *mut ::core::ffi::c_void) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn SetGP(gp: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetGP() -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub static mut _gp: *mut ::core::ffi::c_void;
}
pub const INTC_GS: _bindgen_ty_1 = 0;
pub const INTC_SBUS: _bindgen_ty_1 = 1;
pub const INTC_VBLANK_S: _bindgen_ty_1 = 2;
pub const INTC_VBLANK_E: _bindgen_ty_1 = 3;
pub const INTC_VIF0: _bindgen_ty_1 = 4;
pub const INTC_VIF1: _bindgen_ty_1 = 5;
pub const INTC_VU0: _bindgen_ty_1 = 6;
pub const INTC_VU1: _bindgen_ty_1 = 7;
pub const INTC_IPU: _bindgen_ty_1 = 8;
pub const INTC_TIM0: _bindgen_ty_1 = 9;
pub const INTC_TIM1: _bindgen_ty_1 = 10;
pub const INTC_TIM2: _bindgen_ty_1 = 11;
pub const INTC_SFIFO: _bindgen_ty_1 = 13;
pub const INTC_VU0WD: _bindgen_ty_1 = 14;
#[doc = " EE Interrupt Controller (INTC) interrupt numbers"]
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const DMAC_VIF0: _bindgen_ty_2 = 0;
pub const DMAC_VIF1: _bindgen_ty_2 = 1;
pub const DMAC_GIF: _bindgen_ty_2 = 2;
pub const DMAC_FROM_IPU: _bindgen_ty_2 = 3;
pub const DMAC_TO_IPU: _bindgen_ty_2 = 4;
pub const DMAC_SIF0: _bindgen_ty_2 = 5;
pub const DMAC_SIF1: _bindgen_ty_2 = 6;
pub const DMAC_SIF2: _bindgen_ty_2 = 7;
pub const DMAC_FROM_SPR: _bindgen_ty_2 = 8;
pub const DMAC_TO_SPR: _bindgen_ty_2 = 9;
pub const DMAC_CIS: _bindgen_ty_2 = 13;
pub const DMAC_MEIS: _bindgen_ty_2 = 14;
pub const DMAC_BEIS: _bindgen_ty_2 = 15;
#[doc = " EE Direct Memory Access Controller (DMAC) interrupt numbers"]
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ee_sema {
    pub count: ::core::ffi::c_int,
    pub max_count: ::core::ffi::c_int,
    pub init_count: ::core::ffi::c_int,
    pub wait_threads: ::core::ffi::c_int,
    pub attr: u32_,
    pub option: u32_,
}
pub type ee_sema_t = t_ee_sema;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ee_thread {
    pub status: ::core::ffi::c_int,
    pub func: *mut ::core::ffi::c_void,
    pub stack: *mut ::core::ffi::c_void,
    pub stack_size: ::core::ffi::c_int,
    pub gp_reg: *mut ::core::ffi::c_void,
    pub initial_priority: ::core::ffi::c_int,
    pub current_priority: ::core::ffi::c_int,
    pub attr: u32_,
    pub option: u32_,
}
pub type ee_thread_t = t_ee_thread;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ee_thread_status {
    pub status: ::core::ffi::c_int,
    pub func: *mut ::core::ffi::c_void,
    pub stack: *mut ::core::ffi::c_void,
    pub stack_size: ::core::ffi::c_int,
    pub gp_reg: *mut ::core::ffi::c_void,
    pub initial_priority: ::core::ffi::c_int,
    pub current_priority: ::core::ffi::c_int,
    pub attr: u32_,
    pub option: u32_,
    pub waitType: u32_,
    pub waitId: u32_,
    pub wakeupCount: u32_,
}
pub type ee_thread_status_t = t_ee_thread_status;
pub const CPU_CONFIG_CPU_CONFIG_ENABLE_DIE: CPU_CONFIG = 0;
pub const CPU_CONFIG_CPU_CONFIG_ENABLE_ICE: CPU_CONFIG = 1;
pub const CPU_CONFIG_CPU_CONFIG_ENABLE_DCE: CPU_CONFIG = 2;
pub const CPU_CONFIG_CPU_CONFIG_DISBLE_DIE: CPU_CONFIG = 3;
pub const CPU_CONFIG_CPU_CONFIG_DISBLE_ICE: CPU_CONFIG = 4;
pub const CPU_CONFIG_CPU_CONFIG_DISBLE_DCE: CPU_CONFIG = 5;
#[doc = " CpuConfig options"]
pub type CPU_CONFIG = ::core::ffi::c_uint;
pub const COP0_INDEX: _bindgen_ty_3 = 0;
pub const COP0_RANDOM: _bindgen_ty_3 = 1;
pub const COP0_ENTRYLO0: _bindgen_ty_3 = 2;
pub const COP0_ENTRYLO1: _bindgen_ty_3 = 3;
pub const COP0_CONTEXT: _bindgen_ty_3 = 4;
pub const COP0_PAGEMASK: _bindgen_ty_3 = 5;
pub const COP0_WIRED: _bindgen_ty_3 = 6;
pub const COP0_BADVADDR: _bindgen_ty_3 = 8;
pub const COP0_COUNT: _bindgen_ty_3 = 9;
pub const COP0_ENTRYHI: _bindgen_ty_3 = 10;
pub const COP0_COMPARE: _bindgen_ty_3 = 11;
pub const COP0_STATUS: _bindgen_ty_3 = 12;
pub const COP0_CAUSE: _bindgen_ty_3 = 13;
pub const COP0_EPC: _bindgen_ty_3 = 14;
pub const COP0_PRID: _bindgen_ty_3 = 15;
pub const COP0_CONFIG: _bindgen_ty_3 = 16;
pub const COP0_BADPADDR: _bindgen_ty_3 = 23;
pub const COP0_DEBUG: _bindgen_ty_3 = 24;
pub const COP0_PERF: _bindgen_ty_3 = 25;
pub const COP0_TAGLO: _bindgen_ty_3 = 28;
pub const COP0_TAGHI: _bindgen_ty_3 = 29;
pub const COP0_ERROREPC: _bindgen_ty_3 = 30;
#[doc = " Cop0 Register for (i)GetCop0 and (i)SetCop0"]
pub type _bindgen_ty_3 = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn _InitSys();
}
unsafe extern "C" {
    pub fn TerminateLibrary();
}
unsafe extern "C" {
    pub fn InitThread() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iWakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iRotateThreadReadyQueue(priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn iSuspendThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn InitTLBFunctions();
}
unsafe extern "C" {
    pub fn InitTLB();
}
unsafe extern "C" {
    pub fn Exit(exit_code: s32) -> !;
}
unsafe extern "C" {
    pub fn ExecPS2(
        entry: *mut ::core::ffi::c_void,
        gp: *mut ::core::ffi::c_void,
        num_args: ::core::ffi::c_int,
        args: *mut *mut ::core::ffi::c_char,
    ) -> s32;
}
unsafe extern "C" {
    pub fn LoadExecPS2(
        filename: *const ::core::ffi::c_char,
        num_args: s32,
        args: *mut *mut ::core::ffi::c_char,
    ) -> !;
}
unsafe extern "C" {
    pub fn ExecOSD(num_args: ::core::ffi::c_int, args: *mut *mut ::core::ffi::c_char) -> !;
}
unsafe extern "C" {
    pub fn InitAlarm();
}
unsafe extern "C" {
    pub fn InitExecPS2();
}
unsafe extern "C" {
    pub fn InitOsd();
}
unsafe extern "C" {
    pub fn PatchIsNeeded() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn InitDebug();
}
unsafe extern "C" {
    pub fn DIntr() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn EIntr() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn EnableIntc(intc: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DisableIntc(intc: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn EnableDmac(dmac: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DisableDmac(dmac: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iEnableIntc(intc: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iDisableIntc(intc: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iEnableDmac(dmac: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iDisableDmac(dmac: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SyncDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn iSyncDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn InvalidDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn iInvalidDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn ResetEE(init_bitfield: u32_);
}
unsafe extern "C" {
    pub fn SetGsCrt(interlace: s16, pal_ntsc: s16, field: s16);
}
unsafe extern "C" {
    pub fn KExit(exit_code: s32) -> !;
}
unsafe extern "C" {
    pub fn _LoadExecPS2(
        filename: *const ::core::ffi::c_char,
        num_args: s32,
        args: *mut *mut ::core::ffi::c_char,
    ) -> !;
}
unsafe extern "C" {
    pub fn _ExecPS2(
        entry: *mut ::core::ffi::c_void,
        gp: *mut ::core::ffi::c_void,
        num_args: ::core::ffi::c_int,
        args: *mut *mut ::core::ffi::c_char,
    ) -> s32;
}
unsafe extern "C" {
    pub fn RFU009(arg0: u32_, arg1: u32_);
}
unsafe extern "C" {
    pub fn AddSbusIntcHandler(
        cause: s32,
        handler: ::core::option::Option<unsafe extern "C" fn(call: ::core::ffi::c_int)>,
    ) -> s32;
}
unsafe extern "C" {
    pub fn RemoveSbusIntcHandler(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn Interrupt2Iop(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn SetVTLBRefillHandler(handler_num: s32, handler_func: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn SetVCommonHandler(handler_num: s32, handler_func: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn SetVInterruptHandler(handler_num: s32, handler_func: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn AddIntcHandler(
        cause: s32,
        handler_func: ::core::option::Option<unsafe extern "C" fn(cause: s32) -> s32>,
        next: s32,
    ) -> s32;
}
unsafe extern "C" {
    pub fn AddIntcHandler2(
        cause: s32,
        handler_func: ::core::option::Option<
            unsafe extern "C" fn(
                cause: s32,
                arg: *mut ::core::ffi::c_void,
                addr: *mut ::core::ffi::c_void,
            ) -> s32,
        >,
        next: s32,
        arg: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn RemoveIntcHandler(cause: s32, handler_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn AddDmacHandler(
        channel: s32,
        handler: ::core::option::Option<unsafe extern "C" fn(channel: s32) -> s32>,
        next: s32,
    ) -> s32;
}
unsafe extern "C" {
    pub fn AddDmacHandler2(
        channel: s32,
        handler: ::core::option::Option<
            unsafe extern "C" fn(
                channel: s32,
                arg: *mut ::core::ffi::c_void,
                addr: *mut ::core::ffi::c_void,
            ) -> s32,
        >,
        next: s32,
        arg: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn RemoveDmacHandler(channel: s32, handler_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _EnableIntc(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn _DisableIntc(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn _EnableDmac(channel: s32) -> s32;
}
unsafe extern "C" {
    pub fn _DisableDmac(channel: s32) -> s32;
}
unsafe extern "C" {
    pub fn SetAlarm(
        time: u16_,
        callback: ::core::option::Option<
            unsafe extern "C" fn(alarm_id: s32, time: u16_, common: *mut ::core::ffi::c_void),
        >,
        common: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn _SetAlarm(
        time: u16_,
        callback: ::core::option::Option<
            unsafe extern "C" fn(alarm_id: s32, time: u16_, common: *mut ::core::ffi::c_void),
        >,
        common: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn ReleaseAlarm(alarm_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _ReleaseAlarm(alarm_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iEnableIntc(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iDisableIntc(cause: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iEnableDmac(channel: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iDisableDmac(channel: s32) -> s32;
}
unsafe extern "C" {
    pub fn iSetAlarm(
        time: u16_,
        callback: ::core::option::Option<
            unsafe extern "C" fn(alarm_id: s32, time: u16_, common: *mut ::core::ffi::c_void),
        >,
        common: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn _iSetAlarm(
        time: u16_,
        callback: ::core::option::Option<
            unsafe extern "C" fn(alarm_id: s32, time: u16_, common: *mut ::core::ffi::c_void),
        >,
        common: *mut ::core::ffi::c_void,
    ) -> s32;
}
unsafe extern "C" {
    pub fn iReleaseAlarm(alarm_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iReleaseAlarm(alarm_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn CreateThread(thread: *mut ee_thread_t) -> s32;
}
unsafe extern "C" {
    pub fn DeleteThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn StartThread(thread_id: s32, args: *mut ::core::ffi::c_void) -> s32;
}
unsafe extern "C" {
    pub fn ExitThread();
}
unsafe extern "C" {
    pub fn ExitDeleteThread();
}
unsafe extern "C" {
    pub fn TerminateThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iTerminateThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn ChangeThreadPriority(thread_id: s32, priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn iChangeThreadPriority(thread_id: s32, priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn RotateThreadReadyQueue(priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iRotateThreadReadyQueue(priority: s32) -> s32;
}
unsafe extern "C" {
    pub fn ReleaseWaitThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iReleaseWaitThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn GetThreadId() -> s32;
}
unsafe extern "C" {
    pub fn _iGetThreadId() -> s32;
}
unsafe extern "C" {
    pub fn ReferThreadStatus(thread_id: s32, info: *mut ee_thread_status_t) -> s32;
}
unsafe extern "C" {
    pub fn iReferThreadStatus(thread_id: s32, info: *mut ee_thread_status_t) -> s32;
}
unsafe extern "C" {
    pub fn SleepThread() -> s32;
}
unsafe extern "C" {
    pub fn WakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iWakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn CancelWakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iCancelWakeupThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn SuspendThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn _iSuspendThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn ResumeThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iResumeThread(thread_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn RFU059() -> u8_;
}
unsafe extern "C" {
    pub fn SetupThread(
        gp: *mut ::core::ffi::c_void,
        stack: *mut ::core::ffi::c_void,
        stack_size: s32,
        args: *mut ::core::ffi::c_void,
        root_func: *mut ::core::ffi::c_void,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn SetupHeap(heap_start: *mut ::core::ffi::c_void, heap_size: s32);
}
unsafe extern "C" {
    pub fn EndOfHeap() -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn CreateSema(sema: *mut ee_sema_t) -> s32;
}
unsafe extern "C" {
    pub fn DeleteSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn SignalSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iSignalSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn WaitSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn PollSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn iPollSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn ReferSemaStatus(sema_id: s32, sema: *mut ee_sema_t) -> s32;
}
unsafe extern "C" {
    pub fn iReferSemaStatus(sema_id: s32, sema: *mut ee_sema_t) -> s32;
}
unsafe extern "C" {
    pub fn iDeleteSema(sema_id: s32) -> s32;
}
unsafe extern "C" {
    pub fn SetOsdConfigParam(addr: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetOsdConfigParam(addr: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetGsHParam(
        addr1: *mut ::core::ffi::c_void,
        addr2: *mut ::core::ffi::c_void,
        addr3: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn GetGsVParam() -> s32;
}
unsafe extern "C" {
    pub fn SetGsHParam(
        addr1: *mut ::core::ffi::c_void,
        addr2: *mut ::core::ffi::c_void,
        addr3: *mut ::core::ffi::c_void,
        addr4: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn SetGsVParam(arg1: s32);
}
unsafe extern "C" {
    pub fn PutTLBEntry(
        PageMask: ::core::ffi::c_uint,
        EntryHi: ::core::ffi::c_uint,
        EntryLo0: ::core::ffi::c_uint,
        EntryLo1: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iPutTLBEntry(
        PageMask: ::core::ffi::c_uint,
        EntryHi: ::core::ffi::c_uint,
        EntryLo0: ::core::ffi::c_uint,
        EntryLo1: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn _SetTLBEntry(
        index: ::core::ffi::c_uint,
        PageMask: ::core::ffi::c_uint,
        EntryHi: ::core::ffi::c_uint,
        EntryLo0: ::core::ffi::c_uint,
        EntryLo1: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iSetTLBEntry(
        index: ::core::ffi::c_uint,
        PageMask: ::core::ffi::c_uint,
        EntryHi: ::core::ffi::c_uint,
        EntryLo0: ::core::ffi::c_uint,
        EntryLo1: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn GetTLBEntry(
        index: ::core::ffi::c_uint,
        PageMask: *mut ::core::ffi::c_uint,
        EntryHi: *mut ::core::ffi::c_uint,
        EntryLo0: *mut ::core::ffi::c_uint,
        EntryLo1: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iGetTLBEntry(
        index: ::core::ffi::c_uint,
        PageMask: *mut ::core::ffi::c_uint,
        EntryHi: *mut ::core::ffi::c_uint,
        EntryLo0: *mut ::core::ffi::c_uint,
        EntryLo1: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn ProbeTLBEntry(
        EntryHi: ::core::ffi::c_uint,
        PageMask: *mut ::core::ffi::c_uint,
        EntryLo0: *mut ::core::ffi::c_uint,
        EntryLo1: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn iProbeTLBEntry(
        EntryHi: ::core::ffi::c_uint,
        PageMask: *mut ::core::ffi::c_uint,
        EntryLo0: *mut ::core::ffi::c_uint,
        EntryLo1: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn ExpandScratchPad(page: ::core::ffi::c_uint) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn EnableIntcHandler(cause: u32_);
}
unsafe extern "C" {
    pub fn iEnableIntcHandler(cause: u32_);
}
unsafe extern "C" {
    pub fn DisableIntcHandler(cause: u32_);
}
unsafe extern "C" {
    pub fn iDisableIntcHandler(cause: u32_);
}
unsafe extern "C" {
    pub fn EnableDmacHandler(channel: u32_);
}
unsafe extern "C" {
    pub fn iEnableDmacHandler(channel: u32_);
}
unsafe extern "C" {
    pub fn DisableDmacHandler(channel: u32_);
}
unsafe extern "C" {
    pub fn iDisableDmacHandler(channel: u32_);
}
unsafe extern "C" {
    pub fn KSeg0(arg1: s32);
}
unsafe extern "C" {
    pub fn EnableCache(cache: s32) -> s32;
}
unsafe extern "C" {
    pub fn DisableCache(cache: s32) -> s32;
}
unsafe extern "C" {
    pub fn GetCop0(reg_id: s32) -> u32_;
}
unsafe extern "C" {
    pub fn FlushCache(operation: s32);
}
unsafe extern "C" {
    pub fn CpuConfig(config: u32_) -> u32_;
}
unsafe extern "C" {
    pub fn iGetCop0(reg_id: s32) -> u32_;
}
unsafe extern "C" {
    pub fn iFlushCache(operation: s32);
}
unsafe extern "C" {
    pub fn iCpuConfig(config: u32_) -> u32_;
}
unsafe extern "C" {
    pub fn SetCPUTimerHandler(handler: ::core::option::Option<unsafe extern "C" fn()>);
}
unsafe extern "C" {
    pub fn SetCPUTimer(compval: s32);
}
unsafe extern "C" {
    pub fn SetOsdConfigParam2(config: *mut ::core::ffi::c_void, size: s32, offset: s32);
}
unsafe extern "C" {
    pub fn GetOsdConfigParam2(config: *mut ::core::ffi::c_void, size: s32, offset: s32);
}
unsafe extern "C" {
    pub fn GsGetIMR() -> u64_;
}
unsafe extern "C" {
    pub fn iGsGetIMR() -> u64_;
}
unsafe extern "C" {
    pub fn GsPutIMR(imr: u64_) -> u64_;
}
unsafe extern "C" {
    pub fn iGsPutIMR(imr: u64_) -> u64_;
}
unsafe extern "C" {
    pub fn SetPgifHandler(handler: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn SetVSyncFlag(arg1: *mut u32_, arg2: *mut u64_);
}
unsafe extern "C" {
    pub fn SetSyscall(syscall_num: s32, handler: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn _print(fmt: *const ::core::ffi::c_char, ...);
}
unsafe extern "C" {
    pub fn sceSifStopDma();
}
unsafe extern "C" {
    pub fn sceiSifDmaStat(trid: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn isceSifSetDma(
        dmat: *mut SifDmaTransfer_t,
        count: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn sceSifSetDChain();
}
unsafe extern "C" {
    pub fn isceSifSetDChain();
}
unsafe extern "C" {
    pub fn sceSifSetReg(
        register_num: u32_,
        register_value: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn sceSifGetReg(register_num: u32_) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn _ExecOSD(num_args: ::core::ffi::c_int, args: *mut *mut ::core::ffi::c_char) -> !;
}
unsafe extern "C" {
    pub fn Deci2Call(arg1: s32, arg2: *mut u32_) -> s32;
}
unsafe extern "C" {
    pub fn PSMode();
}
unsafe extern "C" {
    pub fn MachineType() -> s32;
}
unsafe extern "C" {
    pub fn GetMemorySize() -> s32;
}
unsafe extern "C" {
    pub fn _GetGsDxDyOffset(
        mode: ::core::ffi::c_int,
        dx: *mut ::core::ffi::c_int,
        dy: *mut ::core::ffi::c_int,
        dw: *mut ::core::ffi::c_int,
        dh: *mut ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn _InitTLB() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn SetMemoryMode(mode: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn GetMemoryMode() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn _SyncDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn _InvalidDCache(start: *mut ::core::ffi::c_void, end: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetSyscallHandler(syscall_no: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn GetExceptionHandler(except_no: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn GetInterruptHandler(intr_no: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn kCopy(
        dest: *mut ::core::ffi::c_void,
        src: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn kCopyBytes(
        dest: *mut ::core::ffi::c_void,
        src: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn Copy(
        dest: *mut ::core::ffi::c_void,
        src: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn setup(syscall_num: ::core::ffi::c_int, handler: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn GetEntryAddress(syscall: ::core::ffi::c_int) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn init_scr();
}
unsafe extern "C" {
    pub fn scr_printf(arg1: *const ::core::ffi::c_char, ...);
}
unsafe extern "C" {
    pub fn scr_vprintf(format: *const ::core::ffi::c_char, opt: va_list);
}
unsafe extern "C" {
    pub fn scr_putchar(
        x: ::core::ffi::c_int,
        y: ::core::ffi::c_int,
        color: u32_,
        ch: ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn ps2GetStackTrace(results: *mut ::core::ffi::c_uint, max: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn scr_setXY(x: ::core::ffi::c_int, y: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn scr_getX() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn scr_getY() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn scr_clear();
}
unsafe extern "C" {
    pub fn scr_clearline(Y: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn scr_clearchar(X: ::core::ffi::c_int, Y: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn scr_setbgcolor(color: u32_);
}
unsafe extern "C" {
    pub fn scr_setfontcolor(color: u32_);
}
unsafe extern "C" {
    pub fn scr_setcursorcolor(color: u32_);
}
unsafe extern "C" {
    pub fn scr_setCursor(enable: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn scr_getCursor() -> ::core::ffi::c_int;
}
pub type __builtin_va_list = *mut ::core::ffi::c_void;
