#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]


use core::ffi::{c_char, c_int};
use core::fmt::{self, Write};

// Pull in the bindings generated by build.rs
include!("./bindings.rs");

pub struct LibcConsole;

impl Write for LibcConsole {
    fn write_str(&mut self, s: &str) -> fmt::Result {
        // "%.*s" requires two arguments: the length (int) and the string pointer (char*)
        // We append \0 to the format string itself so C knows where the format string ends.
        let format_str = "%.*s\0";

        unsafe {
            printf(
                format_str.as_ptr() as *const c_char,
                s.len() as c_int,
                s.as_ptr() as *const c_char,
            );
        }
        Ok(())
    }
}

// #[doc(hidden)]
// pub fn _print(args: core::fmt::Arguments) {
//     let mut console = LibcConsole;
//     let _ = console.write_fmt(args);
// }

#[macro_export]
macro_rules! print {
    ($($arg:tt)*) => {
        $crate::_print(core::format_args!($($arg)*));
    };
}

#[macro_export]
macro_rules! println {
    () => {
        $crate::print!("\r\n");
    };
    ($($arg:tt)*) => {
        $crate::_print(core::format_args!($($arg)*));
        $crate::_print(core::format_args!("\r\n"));
    };
}



// unsafe extern "C" {
//     pub fn init_scr();
//     pub fn scr_printf(format: *const u8, ...) -> i32;
//     pub fn SleepThread();
//     pub fn printf(format: *const core::ffi::c_char, ...) -> core::ffi::c_int;
// }

// #[unsafe(no_mangle)]
// pub unsafe extern "C" fn pthread_init() {
//     // Optionally initialize anything your custom threading needs here
// }

// #[unsafe(no_mangle)]
// pub unsafe extern "C" fn pthread_terminate() {
//     // Teardown code
// }

// #[unsafe(no_mangle)]
// pub unsafe extern "C" fn pthread_mutex_lock(_mutex: *mut core::ffi::c_void) -> core::ffi::c_int {
//     0
// }

// #[unsafe(no_mangle)]
// pub unsafe extern "C" fn pthread_mutex_unlock(_mutex: *mut core::ffi::c_void) -> core::ffi::c_int {
//     0
// }

// #[unsafe(no_mangle)]
// pub unsafe extern "C" fn pthread_mutex_init(
//     _mutex: *mut core::ffi::c_void,
//     _attr: *const core::ffi::c_void,
// ) -> core::ffi::c_int {
//     0
// }

// #[unsafe(no_mangle)]
// pub unsafe extern "C" fn pthread_mutex_destroy(_mutex: *mut core::ffi::c_void) -> core::ffi::c_int {
//     0
// }

// pub fn add(left: u64, right: u64) -> u64 {
//     left + right
// }

// #[cfg(test)]
// mod tests {
//     use super::*;

//     #[test]
//     fn it_works() {
//         let result = add(2, 2);
//         assert_eq!(result, 4);
//     }
// }
