#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// use libc::posix::{printf, write, puts};
use core::ffi::c_char;
use core::fmt::{self, Write};
use cstr_core::CString;

// Pull in the bindings generated by build.rs
include!("./bindings.rs");

// unsafe extern "C" {
//     // Standard POSIX write. File descriptor 1 is stdout.
//     pub fn write(fd: i32, buf: *const c_void, count: usize) -> isize;
//     pub fn putchar(c: i32) -> i32;
// }

pub struct LibcConsole;

impl Write for LibcConsole {
    fn write_str(&mut self, s: &str) -> fmt::Result {

        let format = CString::new("%s").expect("Failed to create string.");
        let string = CString::new(s).expect("Failed to create string.");

        unsafe {
            // Print to stdout.
            _print(string.as_ptr());

            // printf(format.as_ptr(), string.as_ptr());

            // puts(string.as_ptr());

            // Print to display.
            scr_printf(string.as_ptr());
        }

        Ok(())
    }
}

#[doc(hidden)]
pub fn _printdebug(args: core::fmt::Arguments) {
    let mut console = LibcConsole;
    let _ = console.write_fmt(args);
}

#[macro_export]
macro_rules! print {
    ($($arg:tt)*) => {
        $crate::_printdebug(core::format_args!($($arg)*));
    };
}

#[macro_export]
macro_rules! println {
    () => {
        $crate::print!("\r\n");
    };
    ($($arg:tt)*) => {
        $crate::_printdebug(core::format_args!($($arg)*));
        $crate::_printdebug(core::format_args!("\r\n"));
    };
}

// pub fn add(left: u64, right: u64) -> u64 {
//     left + right
// }

// #[cfg(test)]
// mod tests {
//     use super::*;

//     #[test]
//     fn it_works() {
//         let result = add(2, 2);
//         assert_eq!(result, 4);
//     }
// }
