#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// use libc::posix::{printf, write, puts};

// Pull in the bindings generated by build.rs
mod raw {
    include!("bindings.rs");
}

pub mod kernel {
    pub use crate::raw::{
        // Add kernel functions/types here
        _exit,
        Exit,
        SleepThread,
        WakeupThread,
    };
}

pub mod debug {
    pub use crate::raw::{
        init_scr, ps2GetStackTrace, scr_clear, scr_clearchar, scr_clearline, scr_getCursor,
        scr_getX, scr_getY, scr_printf, scr_putchar, scr_setCursor, scr_setXY, scr_setbgcolor,
        scr_setcursorcolor, scr_setfontcolor, scr_vprintf,
    };
}

/// Graphics Synthesizer Kit bindings
pub mod gs {
    pub use crate::raw::{
        gsKit_TexManager_bind,
        gsKit_TexManager_free,
        gsKit_TexManager_init,
        gsKit_TexManager_invalidate,
        gsKit_TexManager_nextFrame,
        gsKit_TexManager_setmode,
        gsKit_add_finish_handler,
        gsKit_add_hsync_handler,
        gsKit_add_vsync_handler,
        gsKit_alloc_ucab,
        gsKit_check_rom,
        gsKit_clear,
        gsKit_deinit_global,
        gsKit_display_buffer,
        gsKit_finish,
        gsKit_fontm_print_scaled,
        gsKit_fontm_unpack,
        gsKit_fontm_unpack_raw,
        gsKit_fontm_unpack_raw_1,
        gsKit_fontm_upload,
        gsKit_free_fontm,
        gsKit_free_ucab,
        gsKit_get_field,
        gsKit_hires_deinit_global,
        gsKit_hires_flip,
        gsKit_hires_flip_ext,
        gsKit_hires_init_global,
        gsKit_hires_init_screen,
        gsKit_hires_prepare_bg,
        gsKit_hires_set_bg,
        gsKit_hires_sync,
        gsKit_hsync_wait,
        gsKit_init_fontm,
        gsKit_init_global_custom,
        gsKit_init_screen,
        gsKit_lock_buffer,
        gsKit_lock_status,
        gsKit_mode_switch,
        gsKit_prim_line_3d,
        gsKit_prim_line_goraud_3d,
        gsKit_prim_line_strip,
        gsKit_prim_line_strip_3d,
        gsKit_prim_list_line_goraud_3d,
        gsKit_prim_list_points,
        gsKit_prim_list_sprite_flat,
        gsKit_prim_list_sprite_flat_color,
        gsKit_prim_list_sprite_gouraud_3d,
        gsKit_prim_list_triangle_goraud_texture_stq_3d,
        gsKit_prim_list_triangle_goraud_texture_uv_3d,
        gsKit_prim_list_triangle_gouraud_3d,
        gsKit_prim_point,
        gsKit_prim_quad_3d,
        gsKit_prim_quad_goraud_texture_3d,
        gsKit_prim_quad_gouraud_3d,
        gsKit_prim_quad_texture_3d,
        gsKit_prim_sprite,
        gsKit_prim_sprite_striped_texture_3d,
        gsKit_prim_sprite_texture_3d,
        gsKit_prim_triangle_3d,
        gsKit_prim_triangle_fan,
        gsKit_prim_triangle_fan_3d,
        gsKit_prim_triangle_fan_texture,
        gsKit_prim_triangle_fan_texture_3d,
        gsKit_prim_triangle_goraud_texture_3d,
        gsKit_prim_triangle_gouraud_3d,
        gsKit_prim_triangle_strip,
        gsKit_prim_triangle_strip_3d,
        gsKit_prim_triangle_strip_texture,
        gsKit_prim_triangle_strip_texture_3d,
        gsKit_prim_triangle_texture_3d,
        gsKit_queue_exec,
        gsKit_queue_exec_real,
        gsKit_queue_free,
        gsKit_queue_init,
        gsKit_queue_reset,
        gsKit_queue_set,
        gsKit_remove_finish_handler,
        gsKit_remove_hsync_handler,
        gsKit_remove_vsync_handler,
        gsKit_set_clamp,
        gsKit_set_display_offset,
        gsKit_set_dither,
        gsKit_set_dither_matrix,
        gsKit_set_drawfield,
        gsKit_set_finish,
        gsKit_set_primalpha,
        gsKit_set_scissor,
        gsKit_set_test,
        gsKit_set_texclut,
        gsKit_set_texfilter,
        gsKit_setactive,
        gsKit_setup_tbw,
        gsKit_switch_context,
        gsKit_sync_flip,
        gsKit_texture_send,
        gsKit_texture_send_inline,
        gsKit_texture_size,
        gsKit_texture_size_ee,
        gsKit_texture_to_psm16,
        gsKit_texture_upload,
        gsKit_unlock_buffer,
        gsKit_vram_alloc,
        gsKit_vram_clear,
        gsKit_vram_dump,
        gsKit_vsync_nowait,
        gsKit_vsync_wait,
        gskit_prim_list_sprite_texture_uv_3d,
        gskit_prim_list_sprite_texture_uv_flat,
        gskit_prim_list_sprite_texture_uv_flat_color,

        // TODO: consts
    };
}

/// Direct Memory Access Controller Kit bindings
pub mod dma {
    pub use crate::raw::{
        dmaKit_chan_init,
        dmaKit_get_spr,
        dmaKit_init,
        dmaKit_send,
        dmaKit_send_chain,
        dmaKit_send_chain_spr,
        dmaKit_send_chain_ucab,
        dmaKit_send_spr,
        dmaKit_send_ucab,
        dmaKit_spr_alloc,
        dmaKit_spr_begin,
        dmaKit_spr_end,
        dmaKit_wait,
        dmaKit_wait_fast,
        
        // TODO: consts
        DMA_CHANNEL_GIF,
    };
}

// #[macro_use]
pub mod macros;
